### ISSUE TITLE
Feature: Run intersection detection in the background and proactively notify customers

### ISSUE THREAD

**Issue by rparet** [tripleblindmarket/covid-safe-paths#140]
Goal: We should be able to run intersection detection in the background of people's devices and as we get more publicly available data streams and they visit more locations we should proactively notify them if there is an intersection.

**Comment by Utzel-Butzel** [comment]
In https://github.com/wirewirewirewire/pandoa/ I habe implemented this. Do you have a backend server in place? For privacy and server load reasons I download the data of infected patients from the area you are in and do the calcuations on the client without ever uploading your own track records. Would that work for you?
![](https://raw.githubusercontent.com/wirewirewirewire/pandoa/master/assets/images/how-it-works.png)

**Comment by penrods** [comment]
Intersection is now performed in background.
