### ISSUE TITLE
Feature: Distributed health authorities

### ISSUE THREAD

**Issue by rparet** [tripleblindmarket/covid-safe-paths#150]
In the app there will be a config dialog where you can enter your "Trusted Health Authority" (can be multiple of them)

Each authority is basically just a URL (later we will pull a global registry -- it can just be a file within github that is served by rawgit).  But there must always be the ability for a user to type in a unique authority to ensure global usability.

The app GETs that URL and downloads a JSON file:

```json
{ "authority_name":  "Platte County Health Departartment",
  "publish_date": "sometime",
  "info_website": "http://local.authority/website/with/news.html",
  "concern_points": [ { "time": 123, "latitude": 12.34", "longitude": 12.34}, ...]
}
```

With the "info_website" can add a localized tab on the News page.  This allows local authorities to message users.  This is the local news feed, we don't control it.

We use the Authority Name to populate the list box of selected authorities.

We pull the points once a day an run comparisons.

==

Currently News tab opens https://privatekit.mit.edu/views

* Redsigning the news tab to allow customers to choose from different news sources
* Using the above tab to give customers a good overview of what features exist / what is coming.

**Comment by StartupSam** [comment]
Would be great to get information in here from mainstay sources, e.g. CDC, WHO. Adding some summarized symptom and testing info somewhere would also be excellent - offline availability for that info could be quite useful

**Comment by DenisPitcher** [comment]
Has a git file been identified that contains the health authority list?
