### ISSUE TITLE
Functionality to report nearby drive-thru testing centers

### ISSUE THREAD

**Issue by code247** [tripleblindmarket/covid-safe-paths#155]
Users should be able to submit info about local resources like clinics, drive-thru testing centers with appropriate address which can then be made available to other users in a certain radius around that area.

**Comment by E3V3A** [comment]
In what format? I Suggest json.
Please specify the data you want. 
Like: `country, lat, lon, type, address, phone`, 
where **type** would be: `clinic, drive-thru, lab, other`.

**Comment by penrods** [comment]
This will be part of the Healthcare Authorities in the near future release.  Each can provide a locale-specific website to provide information for their constituents.
