### ISSUE TITLE
Log Data on Export Page showing 0 in the first start of the app

### ISSUE THREAD

**Issue by vitorpamplona** [tripleblindmarket/covid-safe-paths#167]
It shows 0 even when there is data on the device. After some time, it showed the correct number of days logged. Most likely a variable that is not ready on the first start for some reason.

**Comment by Rikku-1** [comment]
Is this on ios or android?  I'm not seeing the issue on ios.

**Comment by WriteCodeEveryday** [comment]
android has it every time the app starts... even if there's data there.

**Comment by thetimbanks** [comment]
I am pretty sure this is fixed with this PR https://github.com/tripleblindmarket/private-kit/pull/244
