### ISSUE TITLE
No indicator during Location service failures

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/covid-safe-paths#17]
There are several reasons that location information might not be working properly:
  * GPS has been turned off
  * User disabled the permission under settings
  * Under iOS, app was shutdown in the background
  * Probably others

We need to validate access to GPS and notify/prompt the user when this happens.

**Comment by StartupSam** [comment]
Was this issue completed with #64? If so, should close for housekeeping purposes

**Comment by harshvitra** [comment]
@tremblerz @penrods 

Please check if we can close this 

If not what is the todo for this issue ?
