### ISSUE TITLE
iOS: ITMS-90078: Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by vitorpamplona** [tripleblindmarket/covid-safe-paths#182]
We identified one or more issues with a recent delivery for your app, "Private Kit" 0.5.6 (11). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

**Comment by eyganeshv** [comment]
I fix this problem by enabling push notification capability.

Click on .xcodeproj -> Capabilities -> Enable Push Notification

<img width="1440" alt="Screenshot 2020-04-02 at 11 21 41 AM" src="https://user-images.githubusercontent.com/21999369/78215072-4eabeb80-74d4-11ea-9e4d-f7ff406def40.png">

**Comment by penrods** [comment]
I believe this is fixed now.  Please reopen if not.
