### ISSUE TITLE
How to avoid proximity hit when users are driving?

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#191]
I can't really find any documentation on exactly this app is supposed to work, as the white paper doesn't go into any technical details. But my first concern is how the app will distingsush proximity hit when a person are driving around, and happen to sit in a car next to someone who got COVID. For example at a stop light? 

In this sense, perhaps using BT BLE as in #137 may be a good idea, as a filter. Then it would be acting similar to the successful [TraceTogether](https://www.tracetogether.gov.sg/). #140 may also be relevant.

Then we could use GPS as a coarse grained location (and even inertial sensors, when GPS is blocked). And if there is a hit, activate the BT scan to get better proximity info. 

Any ideas?

**Comment by greggles** [comment]
Not sure how much of this you know, so sorry if I'm repeating anything. Private-kit currently takes locations every 5 minutes. If you are in a car next to someone then the length of time the paths overlap should be pretty minimal, even in a relative rush-hour standstill where 2 cars might trail each other for a while.

At the same time, I think in the case of 2 people on the same bus or same lightrail train it would be useful to know that was a risk of exposure.

I think the app would ideally present it as a possible point of infection and then it's up to the individual to decide for themselves:
* That was my morning commute in my car by myself with the windows rolled up and ventilation set to recirculate. I am not at risk.
* That was a trip on a bus, hmm, I should maybe isolate a bit more and pay a little more attention to my health indicators for the coming days.

**Comment by jmuzzall** [comment]
More edge cases along this thread, but had similar thought, though both are lower probability:

1)  Assumption:  Guidance would be to ignore a path that you cross orthogonally.  I'm not sure if or how data points will be interpolated between the 5 min geo points.  But if you pass at a cross walk or happen to intersect at cross streets in your neighborhood, that is likely no risk.  

2)  If you happen to pass someone going the opposite direction, again is low risk.  You might actually have a matching location with someone if you pass each other as you walk down a street.  Low p of exposure, but path might look similar for a while.  Implies need for clear directionality in path.

**Comment by penrods** [comment]
Potential contact information is provided now in the Exposure History.
