### ISSUE TITLE
Have a package-lock.json *and* a yarn.lock - shouldn't we just have one?

### ISSUE THREAD

**Issue by StartupSam** [tripleblindmarket/covid-safe-paths#227]
Getting a warning in console about different lock versions. Is there any way to enforce using just one (preferably Yarn) for this project?

**Comment by pathakparth** [comment]
@StartupSam -
Temporarily we can disable and remove yarn.lock/package-lock.json files from the project.

Also, add following 2 files on project root which will prevent creating/modifying those files on new commits -
.npmrc -> package-lock=false
.yarnrc -> --install.no-lockfile true 

We can put them back once ready for Production release, but removing them is helpful during development to avoid frequent updates/conflicts on those files.

Let me know and I can raise PR for this.

**Comment by StartupSam** [comment]
@pathakparth Honestly I'm not an expert on git and/or package management, so if you feel like that's a good decision then go for it. I'm sure Steve or Rich or someone else will have thoughts on the PR. Do keep in mind that the app will probably be put into production use within the week, so if having lockfiles is helpful for that, might be a good idea to keep them in.

**Comment by rparet** [comment]
@pathakparth we're talking about this now w/ core dev - please create that PR, that may be what we go with.
