### ISSUE TITLE
Scroll bar and legend for Check Overlap

### ISSUE THREAD

**Issue by andreanuzzo** [tripleblindmarket/covid-safe-paths#235]
As in title: 
- The Check Overlap section would benefit from a scrollbar in the text area, many iOS devices do not show the full text.
- Shouldn't we add a small legend box overlaid on top of the map? With "self" "risk" "overlaps" categories, maybe?

![IMG_1978](https://user-images.githubusercontent.com/36167533/77756490-a5618300-7005-11ea-82fd-b034a417f5dc.png)

**Comment by rparet** [comment]
@andreanuzzo check out the overlap changes that just landed and see if that addresses the above?

**Comment by andreanuzzo** [comment]
This is version 0.5.9 on TestFlight. It looks better (thanks!) but shouldn't we avoid those RED GYNORMOUS circles? 😅 

![IMG_181D6950015D-1](https://user-images.githubusercontent.com/36167533/77865919-be815400-71fe-11ea-92a1-67bbce8e840e.jpeg)

**Comment by penrods** [comment]
No longer part of Safe Paths.
