### ISSUE TITLE
Android app without reliance on Google Play services

### ISSUE THREAD

**Issue by kopolee11** [tripleblindmarket/covid-safe-paths#273]
This is an enhancement request for the Android app. Which is to make a version not reliant on Google Play services. This would make the app useful for 1) people who live in regions where Android devices don't typically have Google Play as well 2) people who purposely run a fork of Android without Google Play services. 

Thanks!

**Comment by E3V3A** [comment]
That's exactly what I would have wanted to to see as well. See #209, #260 and #270. 

I suggest to list the app on any of: 

    Aptoide
    APKMirror
    Amazon Appstore
    F-Droid
    GetJar
    SlideMe
    AppBrain
    MoboGenie
    Galaxy Apps
    GetAPK

Or better yet, just here on github under releases.

**Comment by rparet** [comment]
Thanks for the request! Right now the app uses Google Maps Android API, which is part of the Google Play services platform. That might not be the case in the future, at which point we would definitely consider doing this.

**Comment by E3V3A** [comment]
> Right now the app uses Google Maps Android API, which is part of the Google Play services platform.

Well, apart from OP's issue with not having any Google framework at all on those phones, using *Google Maps* doesn't depend on the *Play Store*. In addition you'd still receive all the data and app stats in the GP Dashboard. So I don't understand the reluctance to have the app published on an alternative location? You buy a phone, and maybe you don't want to have sign up with all the Google credentials right away. 

PS. I've been running all my phones without GP for almost 6 years. Never had an issue that couldn't be easily resolved. Most APK mirrors are just that, they mirror apps and often provide way more info about the apps than GP does, so if private-kit is concerned about privacy, this should also be a rather important priority. In addition it seem that a lot of COVID related app have been pulled off GP, even ones deployed by  states and governments.

**Comment by penrods** [comment]
Originally we were posting the APK files with each release (seee https://github.com/tripleblindmarket/private-kit/releases/tag/0.3).  Recent releases only have the AAB which _can_ be used to produce an APK but it is more difficult, I do understand.  We will strive to include APKs with official releases.

However the notion of not using Google Play is not palatable to me or this project.  The purpose of this app is not to reach the broadest audience possible.  Today, that means the Google Play / Apple App Stores.  As long as the source code is available this does not limit anyone in any way, even if we don't provide the prebuilt APK (which is actually less safe than a store APK, from a security perspective).

Remember, we are literally trying to save the world right now.  Politics (both physical world and virtual world) should be suspended while we band together to do everything we possibly can to help EVERYONE survive this.

**Comment by Amunratis** [comment]
I think you misunderstood @E3V3A The issue here is not about not using Google Play. The main issue is that Google play and all google services are banned in China. https://en.wikipedia.org/wiki/Great_Firewall Remember where it all started. Actually the reason why we even are here is of initial(ongoing?) suppression of facts by the Communist Party of China. In order to make this work we need data, _especially_ from that region. 
     That said, I don't think this should be the highest priority right now? - People aren't traveling right now anyway because of Corona. And maybe it won't be a huge problem to refactor the app so it would be usable behind the firewall of China later on?

**Comment by penrods** [comment]
I do not believe Google services are required in any way since removing the map.  Please start a new issue if this is not true.
