### ISSUE TITLE
No version tags/releases

### ISSUE THREAD

**Issue by filkaris** [tripleblindmarket/covid-safe-paths#299]
Hello!

I have noticed that after version v0.5.8 there are no tags, even though we are currently in version v0.5.11

Since I'm part of a team trying to maintain a fork, it would be great help to actually have tags on the actual version commits. That way we can base off a version and update as we go.

Thank you in advance

**Comment by penrods** [comment]
You are absolutely correct -- this should not happen again.  Apologies.

**Comment by filkaris** [comment]
Really appreciate it :) thank you

**Comment by kenpugsley** [comment]
Thanks for bringing this up.  I will be following up on this.  I'm currently working on a defined codeline / release plan.  I'd like to hold this open until that plan is in place and agreed upon, then we'll close this issue.
