### ISSUE TITLE
Feature: In-app redirect based call service

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/covid-safe-paths#301]
Similar to the customized News based on Geolocation feature we want a call button which takes the user to their call screen in case they want to call the facilities or service, where the phone number will be based on geolocation.

**Comment by NethravathiPuttraju** [comment]
I can implement this feature.

**Comment by NethravathiPuttraju** [comment]
May i know where i should add call button.

**Comment by kenpugsley** [comment]
I don't think this feature has yet been designed for v1.0, so there is likely not a set place right now.  Be aware that this would likely not get pulled in until post v1.0.

**Comment by NethravathiPuttraju** [comment]
I have implemented this feature . Since this feature is not for this version v.1.0 , i can't rise PR for this right?

**Comment by NethravathiPuttraju** [comment]
May i know where can i find phone number , currently news is implemented with static data.

**Comment by penrods** [comment]
This can be done via the Health Authority in HTML.
