### ISSUE TITLE
Pull finegrained data sources in the App

### ISSUE THREAD

**Issue by tremblerz** [tripleblindmarket/covid-safe-paths#313]
Currently, we pull data from the lancet dataset, which is quite coarse, hence using much more accurate data sources would improve the user engagement.
Some examples - https://github.com/nychealth/coronavirus-data/blob/master/tests-by-zcta.csv

**Comment by E3V3A** [comment]
Yep, as long as it doesn't cause confusion as being "real" data.

**Comment by penrods** [comment]
No longer part of Safe Paths.
