### ISSUE TITLE
Malayalam language support (translation)

### ISSUE THREAD

**Issue by saranyaharidas** [tripleblindmarket/covid-safe-paths#314]
Adding malayalam language support (translation)

**Comment by saranyaharidas** [comment]
Please assign this to me, I have started working on this

**Comment by saranyaharidas** [comment]
@alpita-masurkar : will do the translation for Malayalam in new app

**Comment by alpita-masurkar** [comment]
Hey @saranyaharidas 
Thank you for letting me know, will update it in the translation doc.Let me know when you create a PR
- Alpita

**Comment by saranyaharidas** [comment]
Hey @alpita-masurkar , PR is raised for malayalam language

[link](https://github.com/tripleblindmarket/covid-safe-paths/pull/531)
