### ISSUE TITLE
Discussion: consider changing the green martian to just a green dot.

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#316]
I was almost puking when I opened the latest version of the app to a see a huge green gummy bear over my country. Or maybe it was a martian? IMO. This make the app look not very serious and more like a kiddy game. I didn't see any previous discussions about replacing that icon, so what's up with that?

I would have preferred and expected a small green dot that doesn't cover half the country when checking your traces. I am wrong here? Did I miss something?

**Comment by harshvitra** [comment]
I will forward this in the UI XUX channel 
@E3V3A

**Comment by E3V3A** [comment]
@harshvitra  Where is the UI XUX channel. I'm on slack but not found there...

**Comment by penrods** [comment]
No longer part of Safe Paths.
