### ISSUE TITLE
FEATURE REQ: granularity and movement data

### ISSUE THREAD

**Issue by andreanuzzo** [tripleblindmarket/covid-safe-paths#336]
As from title:
- do we have an idea on what is our sensitivity? Based on #335 seems to be 5 meters, might not be enough to spread contagion
- can we overlap on top of public transportation routes and other public places? Maybe using a simulation based on normal traffic? Putting those as some sort of "weight" for the overlap risk?

These would help making the overlap function more accurate and effective.

**Comment by E3V3A** [comment]
Can you state the issue in a more clear way? I.e. What is the problem? What do you propose to fix it?

**Comment by E3V3A** [comment]
On 2nd thought, google does have the time table for most public transport lines, so in theory one should be able to use that data as well, to extract something useful.

**Comment by summetj** [comment]
Current sensitivity is 20m (60ft).
