### ISSUE TITLE
[FR] add alternative map api

### ISSUE THREAD

**Issue by fazlerabbi37** [tripleblindmarket/covid-safe-paths#338]
I don't think depending on Google to get map data would ensure this app's 'privacy-first' motto for a lot of people. I would suggest providing an alternative to it or if possible replace it with an open source alternative provider like OpenStreetMap. 

If I am not wrong the app usages map API for showing overlap and developed using NodeJS. You might want to take a look at [Leaflet JS](https://leafletjs.com/). Though the OpenStreetMap tile server are forbids heavy usages due to it being run on a donated resource (more details here at [tile usages policy](https://operations.osmfoundation.org/policies/tiles)), you can use Mapbox's [vector](https://docs.mapbox.com/vector-tiles/reference) or [raster](https://docs.mapbox.com/api/maps/#raster-tiles) tiles which has a more reliable service at a reasonable [pricing](https://www.mapbox.com/pricing).

Thanks in advance!

**Comment by fazlerabbi37** [comment]
I asked in the Telegram group: [OpenStreetMap Dev](https://t.me/OpenStreetMapDev) and got the suggestion for [StadiaMaps](https://stadiamaps.com). See the [docs](https://stadiamaps.com/products/map-tiles) and [pricing](https://stadiamaps.com/pricing). Hope this helps!

**Comment by E3V3A** [comment]
I doubt there will be any move away from Google as an ex-Google executive is part of the core team here. (I also suggested to not have the app be dependent on using the Play Store... )

But I completely agree with you, when it comes to this simple application, OSM is superior an far easier and lighter to use than G maps. It also show way better details and sensible graphics when it comes to buildings etc. (Aaaand doesn't require you to update your map every week...)

**Comment by penrods** [comment]
No longer part of Safe Paths.
