### ISSUE TITLE
Understand how cam distributed ledgers help with safepaths

### ISSUE THREAD

**Issue by ddutta** [tripleblindmarket/covid-safe-paths#344]
It’s not clear how data and it’s governance might work out for a large distributed group of entities. How can distributed ledger tech help? What key problems do we need to solve at the app level and at the healthcare provider level?

**Comment by penrods** [comment]
Currently, each Healthcare Authority is autonomous.  There is no need for them to coordinate or validate each other, they are only responsible to be trustworthy to their constituents.
