### ISSUE TITLE
Check Overlap - Click to view the public dataset = Crash

### ISSUE THREAD

**Issue by carverofchoice** [tripleblindmarket/covid-safe-paths#346]
From the Private Kit Licenses Screen:
Private Kit
Version 0.5.11
OS: android v28
Screen Resolution: 411X845

Device: Samsung Galaxy Note 8
Model: SM-N950U
Android 9
Sprint

Weeks ago I imported my google GPS data. It worked fine until the latest update (changing from green circles and red location markers to showing people as location markers). 

Now when I 
1) click "Check Overlap" and then 
2) click "Click to view the public dataset" 
it crashes, every time. Since at least 4/2/2020.

Tried force-stop and reload. Tried rebooting phone. 

Attached a video.
[Video of crashing.zip](https://github.com/tripleblindmarket/private-kit/files/4432630/Video.of.crashing.zip)

Opened as new issue since #205 was already closed but the issue persists on my Android.

**Comment by harshvitra** [comment]
Hey @carverofchoice could not run the video

But we have removed this feature completely and added new way of showing overlaps

**Comment by harshvitra** [comment]
@tremblerz we can close this
