### ISSUE TITLE
Traditional Chinese and Simplified Chinese language support (translation)

### ISSUE THREAD

**Issue by ai-entrepreneur** [tripleblindmarket/covid-safe-paths#351]
Please assign the issue to me, I'm working on it, thanks!

**Comment by kenpugsley** [comment]
Please be aware the UI is undergoing a significant update.  You may want to wait 24 hours or so until the UI is updated.

**Comment by alpita-masurkar** [comment]
this should be closed. #493 was merged into dev

**Comment by summetj** [comment]
@ai-entrepreneur  FYI in the PR you said: "Add traditional Chinese support, fixing issue #351"

If you had instead put the "fixes" keyword directly in front of the issue number ("Fixes #351") github would have automatically linked them and this issue would have been auto closed.
