### ISSUE TITLE
Saving identical location/time more than once (on iOS)

### ISSUE THREAD

**Issue by TruffleClock** [tripleblindmarket/covid-safe-paths#360]
This is what I see from printing the _curated_ array in _saveLocation_ right before _SetStoreData_

<img width="553" alt="Screen Shot 2020-04-05 at 4 31 19 PM" src="https://user-images.githubusercontent.com/1556067/78512669-3bf71800-775b-11ea-8db0-8f6a9225ef42.png">

**Comment by kenpugsley** [comment]
Quick note (mostly for myself, possibly for anyone who takes this isssue): looking at https://github.com/mauron85/react-native-background-geolocation it appears that locationInterval is only supported on Android.  Need to research what the correct solution is for iOS.

**Comment by kenpugsley** [comment]
Thanks for the catch on the locationInterval.  Dealt with in #389

**Comment by kenpugsley** [comment]
@TruffleClock Would appreciate your help verifying that the data is now saved at a sane rate.
