### ISSUE TITLE
Potential bugs in LocationService

### ISSUE THREAD

**Issue by TruffleClock** [tripleblindmarket/covid-safe-paths#363]
**Issue 1** 
https://github.com/tripleblindmarket/private-kit/blob/develop/app/services/LocationService.js#L100
Why is it starting another BackgroundGeolocation instance if instanceCount > 1? Why would you want multiple instances?

**Issue 2**
The following callbacks are duplicated in LocationService:
- BackgroundGeolocation.on('stop' ...
- BackgroundGeolocation.on('stationary' ...

**Issue 3**
Backfill logic isn't documented and doesn't seem to make sense. Why is the prior point being duplicated over and over? I think this is the cause of this issue: #360

**Comment by NethravathiPuttraju** [comment]
We can work on Fixing this issue..

**Comment by kenpugsley** [comment]
I think all dealt with in #389
