### ISSUE TITLE
Displaying Map on full screen

### ISSUE THREAD

**Issue by ArchanaNair** [tripleblindmarket/covid-safe-paths#365]
UI Enhancement to Map: 
Displaying Google Map on full screen, with 'Public Dataset'  button as an overlay. An info icon(i) will be
displayed at the top right corner, which tells user what green trail and purple circle represents.

**Comment by ArchanaNair** [comment]
Please assign this enhancement to my name.

**Comment by tremblerz** [comment]
This would be a good enhancement, however, we do not have this feature as part v1.0 of safepaths release. So, it would be great if you can start adding this feature here [Private Kit Repo](https://github.com/PrivateKit/private-kit)

**Comment by E3V3A** [comment]
@tremblerz 
>  we do not have this feature as part v1.0

If the code is already done and working, I don't see a reason to not include it.

@ArchanaNair 
Please provide a screenshot (as requested in PR).

**Comment by ArchanaNair** [comment]
New PR raised for this after updation in latest UI,
PR No:
https://github.com/PrivateKit/private-kit/pull/12

**Comment by penrods** [comment]
Maps are no longer part of Safe Places.
