### ISSUE TITLE
Implement 'findNewAuthorities()'

### ISSUE THREAD

**Issue by Patrick-Erichsen** [tripleblindmarket/covid-safe-paths#375]
I was poking around in the codebase and noticed the [commented instructions for building out `findNewAuthorities()` in `LocationTracking.js`](https://github.com/tripleblindmarket/covid-safe-paths/commit/9c6f32cab7b21b38a79111c63c700d1263ca3292#diff-727aee301c7a491d08372f19508dfde6R165-R173).

I'm looking for a good first issue to tackle and thought I'd give this a go.

@penrods, it looks like you added the comments. Mind if I assign this to myself?

## Outline
- [ ] Pull down the Healthcare Authorities list (see Settings.js)
- [ ] look at the GPS extent box of each authority and (if any of the GPS coordinates change) pop-up a notification that is basically:
  - There is a new "Healthcare Authority" for an area where you have been.
- [ ] Tapping that notification asks if they want to Add that Healthcare Authority under the Settings screen.

**Comment by Patrick-Erichsen** [comment]
If this work is a blocker on any other issues please let me know - I have experience developing React & React Native Web, but I'm pretty new to React Native and mobile in general. I don't want to hold anything else up if it takes longer than I anticipated.

**Comment by Patrick-Erichsen** [comment]
I spent a few hours today trying to figure out how to test `rn-fetch-blog` but couldn't get it to work. 

I wanted to pull down our list of HCAs and verify that we're returning a valid YAML file that has an `Authorities` list, but it doesn't seem like there's a clean way to actually call `RNFetchBlob` in Jest without just mocking out the entire module (https://github.com/wkh237/react-native-fetch-blob/issues/212).

If anyone has any thoughts on how to test this cleanly let me know.

**Comment by penrods** [comment]
Closing this one in favor of #425.
