### ISSUE TITLE
Implement Redux 

### ISSUE THREAD

**Issue by denispapakul** [tripleblindmarket/covid-safe-paths#384]
For future expansion and growth of the application, it is worth connecting the redux store, it will also be useful to get rid of logging in the console. We will be able to switch to the use of Redux-Devtools and competently monitor all the actions that occur. 

For the performance, it’s bad that the logging of code parts will remain on the release version of the application. It should be resolve by Redux. I can implement it.

**Comment by E3V3A** [comment]
Another library, another dependency, another 100 ways to break the app. 
What is the problem this is solving again??

**Comment by jpomazal** [comment]
For what it's worth, I would also vote against this direction.  It adds an unnecessary complexity and ties components to a global state.  If a shared state is needed it can be implemented via Contexts or HOCs rather than adding another layer to the app.
