### ISSUE TITLE
Store all constants in one file

### ISSUE THREAD

**Issue by denispapakul** [tripleblindmarket/covid-safe-paths#385]
I suggest storing all constants in one file in order to avoid code repetition and to use re-use of variables. This problem looks like this - 
<img width="375" alt="Screen Shot 2020-04-08 at 12 57 00 AM" src="https://user-images.githubusercontent.com/47609057/78723994-26d5e100-7935-11ea-9715-7cf27e21ea3e.png">
Can implement it.

**Comment by tremblerz** [comment]
Do you want to take it on? We'll assign it you

**Comment by denispapakul** [comment]
Sure, yes, I will implement it.

**Comment by jpomazal** [comment]
Just a comment on this, `width` isn't inherently a constant.   If screen orientation changes, or if app goes side-by-side, etc. that could change.

To make it more compatible we should probably use a HOC, library or similar where needed and pull references to width out of static styles and change to `style={[style.baseStyle,{width:...]}` where needed, although we might want to consider removing static references in general and use alternative layout strategies.
