### ISSUE TITLE
Potential legal issues with PR #354

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#401]
Looking at the screen shots from PR #354, raise red flags regarding some of the text. 

In particular: 
* *"studying refugee migration."*  - This will most likely cause an insta-ban in countries like: Germany, Scandinavia and the Baltics where strong privacy laws are in place. 
* *"Safe Paths have no affiliation with Google"* - That's simply not true if one of your main project engineers is a former Google executive, while insisting [the app] on being dependent on both Google Maps and Play Store. (See other issues.) We'll become lawyer food in no time.

I suggest removing both those statements.

**Comment by vitorpamplona** [comment]
I don't think affiliation means what you think it means. A project is not "affiliated" because of a FORMER person was working with another entity. The use of Maps does not imply affiliation. The same for the Play Store. Otherwise, all apps would be "affiliated" with Google.

**Comment by E3V3A** [comment]
Well, that' swhy I said this is lawyer food. Navigating through (mostly US) notions, interpretations and legal definitions, will be understood very different elsewhere. (How would you define "affiliated" yourself?) The fact is that there is a clear possibility for conflict of interest, and the forced dependencies show exactly that. Personally, I'm already flat on being fine with that, but I'm commenting as a warning on how I believe those countries will react to that text.

**Comment by penrods** [comment]
The text shown in that PR has all totally changed.  All of that stuff has been removed.

**Comment by penrods** [comment]
Thanks for being watchful, though!  I do appreciate it!!
