### ISSUE TITLE
Enable auto format on save with ESLint integrated with Prettier

### ISSUE THREAD

**Issue by qingqingliu** [tripleblindmarket/covid-safe-paths#407]
Enable auto format on save in VSCode with ESLint integrated with Prettier which brings us with
- Auto format on save
- Enforce rules around importing order,  variable name, unused imports, unused variables etc

**Comment by kenpugsley** [comment]
Thanks for the suggestion.  We've started enforcing this thanks to @tstirrat in the last couple of days.
