### ISSUE TITLE
Push notifications/alerts when user is in proximity of affected patients?

### ISSUE THREAD

**Issue by gokulanv** [tripleblindmarket/covid-safe-paths#418]
A person infected with COVID-19 can mark himself as infected and he/she is advised to self-quarantine by the App. But, if the patient moves out by mistake and comes in the proximity of another user, would it be possible to send red alerts to both of them?

Of course, some people may not mark themselves as infected, but some might. And this can help a lot of people by staying away. And also, privacy of the infected patient must be maintained.
Just a suggestion!

**Comment by penrods** [comment]
This is not in the spirit of this application, IMHO.  This is a contact tracing solution, not "COVID radar".  Achieving the above and retaining privacy is likely not possible or practical.  Just self quarantine!

**Comment by summetj** [comment]
Agreed. Also, the potential for abuse (someone self setting their status to infected just to enjoy watching people gasp at their phone's notifications as they walk by) is immense.  Our model is that the health authority is the only entity who has the ability to determine that an individual is infected and upload data for identifying potential exposures.
