### ISSUE TITLE
FEATURE REQ: Test/demonstrate intersection with infected trails

### ISSUE THREAD

**Issue by penrods** [tripleblindmarket/covid-safe-paths#423]
While testing and demonstrating it would be useful to be able to see the interface that is shown when you cross paths with an infected individual.  The following is a decent scheme for achieving this:

* Add a handler for clicking on the Team icon in the About box.  Have the page-open reset a state variable to 0, then increment it once each tap.  If they get to 3(?) taps, toggle the test mode described here.  Perhaps change the displayed icon?
* In "test" mode, run code similar to the [DEBUGGING CODE](https://github.com/tripleblindmarket/covid-safe-paths/blob/develop/app/views/Notification.js#L90) in Notification.js
* Have the code save fake counts to the CROSSED_PATHS StoreData.  This information gets regenerated once every 12 h ours.  It should also set a TEST_DATA boolean to true
* On the main page, if TEST_DATA is set you should not run the intersection that occurs on page load.
* On the Exposure History page you should see the results
* Going back to About and triple-tapping can immediately reset the flag and run another intersection to fill the CROSSED_PATHS array correctly.

**Comment by kenpugsley** [comment]
Two other points on this ...
- We would probably need some kind of marker on the pages to indicate "DEMO MODE".
- An alternate possiblity for entering "demo mode" would be to enter a special url for a provider ... perhaps something like "__demomode__".
