### ISSUE TITLE
Build Script Should Provision Yarn If It's Not Set Up

### ISSUE THREAD

**Issue by efalkner** [tripleblindmarket/covid-safe-paths#429]
If a user does not have `yarn` globally installed and available on the command line when they run the `dev_setup.sh` script, it will throw an error on running `npm install`, as we are now using a `yarn.lock` file. 

Recommended fix: update the setup script to install yarn globally if it is not found on the command line.
Execute `yarn global add` vs `npm global install`,  and update the install command to `yarn`.

**Comment by kenpugsley** [comment]
Would be a great thing to add to the dev_setup script.  Please submit a PR if you're so inclined.
