### ISSUE TITLE
Bahasa Support

### ISSUE THREAD

**Issue by khairu-aqsara** [tripleblindmarket/covid-safe-paths#435]
There is a need for translation for Bahasa Indonesia, A locales package for Indonesia translation is needed. Supported locale code is 'id', 

It is ok to add new translation right now?

**Comment by alpita-masurkar** [comment]
Hi @khairu-aqsara, yes that'd be great! You can start adding translation now.
One thing to remember- the name Safe Paths does not change to it's meaning in local languages since it is the identity of this app.

Are you also on our slack channel?

**Comment by khairu-aqsara** [comment]
thank you @alpita-masurkar,
in Bahasa/Indonesian language there is no special local script for `Safe Paths` name, 
I think using `Safe Paths` as a name still more easier to understand.

**Comment by alpita-masurkar** [comment]
Ok. that sounds good. Will look forward to your PR

**Comment by alpita-masurkar** [comment]
We've already merged the PR related to this. I'm closing this issue.
