### ISSUE TITLE
CONCERN: App does not provide clear actions for the user, in the event of "red" status DHM-S1-2

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#443]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

The whole purpose of the app is to affect user behaviour.  We maximize our chances of this by providing really clear instructions on what users should do.

Self-isolate?
Review their exposure history, and act based on that?  Folloowing what guidance?
Contact their healthcare provider.

Just providing info that they may be infected without clear steps means we risk missing important opportunities to fix behaviour.

(note: I have not been able to actually test this function yet due to other defects.  This concern is raised on the basis of the screenshots I have seen).

**Comment by summetj** [comment]
Closing - suggestion for new behavior (updates to specification document) as opposed to issue with code.  

It's not a bad suggestion, but should be taken up with the specifications developers.
