### ISSUE TITLE
CONCERN: Is Binary red/green status the best way to communicate to the user?  DHM S1-3

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#444]
https://docs.google.com/document/d/1pDnPnIbNHlk1SoZC65eHsvKvKOaZp4Xg8vlpZiyVPDY/edit

Maybe there is research or analysis supporting this presentation to the user, but I have not seen it.

I would have thought some overall risk score, which could be mapped to particular actions or behaviors (potentially factoring in other factors like the user's age etc.) would be better than a binary red/green status.

**Comment by E3V3A** [comment]
Yep, I mentioned this in #309 like this:

---
> In China:

1. **`GREEN:`** - The person has either **"recovered"** or doesn't have it. 
1. **`ORANGE:`** - The person has **"unknown"** status or pending test results
1. **`RED:`** - The person is **"infected"** and is under quarantine.

This should be improved upon to separate the green into 2 different results. I suggest:

1. **`BLUE:`** - The person is **"susceptible"** but doesn't have it. (Negative *antigen-test* AND negative *antibody*-test.)
1. **`GREEN:`** - The person has passed an *antibody-based* test. (Independently recovered)

**Comment by summetj** [comment]
Possibly not the best way to communicate to the user, but the primary goal is to alert the user to possible exposure.  The specification has a "green" (not exposed) and "yellow" (may have been exposed) binary distinction at the moment. Closing issue as the app follows the specification.
