### ISSUE TITLE
CONCERN: App doesn't provide any info to help user to avoid infection - DHM-S1-4

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#445]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

In a pandemic, we all want to
1 - avoid getting infected
2 - avoid infecting others, should we become infected.

While 2 is a motivator, 1 is likely to be a much stronger motivator.

At the moment, the app only seems to offer info that helps with 2.

Function that appears to support 1 (e.g. maps showing where infected people have been) could be valuable in encouraging adoption of the App.

Motivation 2 by itself may not be enough to drive the widespread adoption of the app that we want to see.

**Comment by diarmidmackenzie** [comment]
I wrote this comment on slack: https://covidsafepaths.slack.com/archives/C010YHFGLCV/p1586685167194800?thread_ts=1586623279.184800&cid=C010YHFGLCV

Steve - I think this is relevant to this issue, which I raised out of initial testing I did of the app.
https://github.com/tripleblindmarket/covid-safe-paths/issues/445
You are saying that there is nothing that we can possibly do in the app to help a user avoid getting infected - all we can do is help them to assess the risk that they are infected, and hence make better choices about who else they expose.
If so, I think there is work to be done around messaging here.
The App name "Safe Paths" suggests (to me at least) that it can help you avoid getting infected (by choosing safe paths).
I suspect users are generally more interested in protecting themselves than others.
Is the strategy:
give them the impression the app will help them be able to protect themselves, to encourage downloads / usage, and hope that users don't notice / aren't bothered that in fact all the app does is help them to avoid protecting others.
or: be clear from the start that the purpose of this app is to protect others, not to protect yourself...?
I don't know what the fix is, but I'm uncomfortable about the alignment between the positioning/naming of the app & what its capabilities actually are.

**Comment by penrods** [comment]
The Mayo link on the main page provides this sort of info in a globally accepted way.  Individual authorities can provide local info.  I don't think we can do much more without crossing boundaries and limiting the ability for this to be used globally -- some countries might have different healthcare recommendations, there is not global truth.

I also disagree with your "individual first" outlook.  No person can save themselves.  This HAS to be a community effort or we are never going to leave out homes.  By participating and using this app along with the rest of your community, you are helping yourself by stopping the next phase of outbreak.

**Comment by E3V3A** [comment]
@penrods 
> The Mayo link on the main page provides this sort of info in a globally accepted way. Individual authorities can provide local info. I don't think we can do much more without crossing boundaries and limiting the ability for this to be used globally -- some countries might have different healthcare recommendations, there is not global truth.

I feel this is becoming a little bit too much (geo?) political. On the one hand you're trying to *sell* this app to all sorts of countries around the world, while on the other, you're locking yourself into something that is purely relevant to the US and all the legal BS that can occur there. 

Either way, if there is something this pandemic is reminding us (with a slap in the face) every day, is that we cannot rely on our authorities fro our own well being, and the only ones that is going to save us are ourselves and the community we're part of. Therefore I strongly disagree with your statement above. BUT, in case this is such a huge issue in the US, it is also equally trivial to implement local - per country settings in the app, to prevent certain types of usage. 

For example, the usage of heat maps etc, that for some (still unknown) reason was removed.

**Comment by summetj** [comment]
App currently has link to Mayo clinic. Extra functionality removed for MVP rollout. Additional features will be included in future version specifications.
