### ISSUE TITLE
CONCERN: App intro screens are not suitable for contact tracing use case - DHM-S1-5 DHM_URGENT

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#446]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

The intro screens are oriented towards an undiagnosed user.  As a diagnosed user, being directed to use this app by a Healthcare Authority for Contact Tracing, I would not find the messaging reassuring, and could find it upsetting e.g “The way back to normal starts here”, “If you cross paths with someone who already has COVID-19….”

**Comment by diarmidmackenzie** [comment]
If we are going live with a specific target of pitching the app for Contact Tracing, I think it is very urgent that we resolve this.

**Comment by penrods** [comment]
I understand what you are saying.  I have a few thoughts:
* This is still the way back to normal.  Their participation is part of the Community effort. 
* They won't happen upon this app in a void if they were just diagnosed.  They will be in direct contact with a human at the healthcare authority who is counseling them.  That will be more effective than any text.  These are the same kinds of people who deliver HIV diagnoses.
* Changing text is difficult at this stage.  We have approval from Mayo, and making a change would push back any launch.

**Comment by diarmidmackenzie** [comment]
OK - understood.

Perhaps we can compensate for this in our briefing to the contact tracers who will be on the phone with the patient?

Difference between e.g.

"We have an app that we use to help with the contact tracing process.".

vs. 

"We have an that we use to help people to monitor their risk of exposure to Covid-19, and we also use that app to support us during this contact tracing process".

Just that little bit of context & expectation setting in the phone conversation could make a big difference in terms of cushioning a potential negative impact on the user of those initial screens.

If I'd just been diagnosed with COVID-19, I think I would be both shocked and scared, and therefore potentially very sensitive to even apparently trivial things,

**Comment by penrods** [comment]
Absolutely!  I've have conversations with several contact tracers and they are fully aware of the shock of the message they are delivering.  There have been unfortunate cases where newly diagnosed patients just hang up the phone when it has to be delivered remotely.  They are absolutely working to address these processes.

Since this isn't a technical issue with our app, I am going to go ahead and close this issue.  I do appreciate the thoughtfulness, know that it is being considered by policymakers and for training.

**Comment by diarmidmackenzie** [comment]
@penrods Having mulled this over, my preference would be to defer this, so it's left open for consideration in a future release, rather than closing.  And (at some point, maybe not right now) to trigger a conversation with Mayo on this.

Reasoning
- Completely acknowledge that for initial release, we can't change this.
- However the fact that Mayo have such a tight approval process around the text suggest they really do care about the fine details here.
- Therefore I suspect that in reviewing the text, they simply did not consider that this same text will also be presented in the diagnosed patient use case.  If they have, I feel confident this topic would have been raised before.
- Therefore I think it would be better to highltight this point to Mayo, and see what their take is....

But given we don't want to disrupt the imminent release, it might make sense to not ask that question right now.

Perhaps once the release is out the door, we could take this observation to Mayo, and see what their thoughts are?

I'm happy to accept the text is "final" for this upcoming release.  I'm much less happy with the idea that it is "final" in the sense that it will never change from this point on.  I don't think anything in the app should be "final" in that sense.
