### ISSUE TITLE
BUG: After setup workflow, app reports "All finished", but key config is missing - DHM-S1-6

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#447]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

[DHM-S1-6] The “All finished” screen implies to the user they have done all the setup needed to use the app.  This is misleading, as for the app to provide benefits, they also need to add Healthcare Authorities (and also, ideally, import their location history)
o   Suggestion: incorporate both these steps into the initial setup flow.

Especially in combination with https://github.com/tripleblindmarket/covid-safe-paths/issues/442 this risks misleading the user about their level of risk.

**Comment by summetj** [comment]
Closed by #657.
