### ISSUE TITLE
BUG: Google account not populated by default when importing location data DHM-S1-10

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#450]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

o   [DHM-S1-10 ] Since I am already logged into my google account in my Android phone, I had expected my google account email address to be auto-populated.

The account was blank, and had to be filled in manually.

However rather than fixing this, I'd prefer we overhaul the whole thing as per: https://github.com/tripleblindmarket/covid-safe-paths/issues/69

**Comment by summetj** [comment]
I'm going to close this as #410 has merged, feel free to re-open or re-create if that didn't resolve it.
