### ISSUE TITLE
BUG: Google warns that location data download could take "hours or days" DHM-S1-11

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#451]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

o    [DHM-S1-11] Google warns “the process can take a long time, possibly hours or days”.  I don’t know whether this is true, but it’s not consistent with the messaging in the SafePaths app.

Actual experience is that download takes minutes.

Rather than trying to fix Google's wording (!) probably best to just target https://github.com/tripleblindmarket/covid-safe-paths/issues/69

**Comment by E3V3A** [comment]
I still don't understand why we need to rely on downloading our own location data from Google. It just doesn't make any sense. We obviously already know our own location.

So can someone explain why this is needed?

**Comment by diarmidmackenzie** [comment]
@E3V3A As I understand it, this is not about determining our current location, but about downloading historical data (14d or so), which Google typically already has.

2 reasons it's useful.

1. As an undiagnosed patient, I can start evaluating my risk level immediately I download the app, rather than having to wait a few days for records of my movements to build up i the app's native loggging.

2. Even more important, in the case of a patient who is diagnosed, they will only download the app when the contact tracer reaches out to them, but it's really important that we gather their full movement history from the preceding 2 weeks.

That said, in case 2, it's not clear why the location data needs to be mediated by the app.  Perhaps they could just download the location data from google, and send directly to the healthcare provider.

Potentially in future the app could offer a more secure/private way of sharing the (unredacted) data with the HC provider, but right now that sharing interface is just an email anyway, so mediating the location data via the app doesn't seem to create any value - they could just dump the data from their Google account and email directly to the HC provider, with no app....

**Comment by diarmidmackenzie** [comment]
All that said, I have a suspicion that Google have recently changed their defaults on storing location data.  They used to store for everyone by default, but recently I think I noticed that this was now something you need to explicitly enable.

I've not researched in any detail, this was just something I noticed in passing, might be worth a bit more digging - given the increased scrutiny on tech giants & privacy, I wouldn't be surprised if they started to change a few default values in favour of privacy...

**Comment by E3V3A** [comment]
I'm not convinced everybody has location services enabled. Interesting:

* https://themanifest.com/app-development/location-tracking-mobile-apps

Either way, it's quite disturbing the amount of details that are in the downloads. I really don't think this data should be sent directly anywhere and it should also be redacted.

**Comment by summetj** [comment]
Closing issue, may re-address after revamped google location import is integrated.
