### ISSUE TITLE
BUG: Inaccurate claim that the app will never share a user's location data - DHM-S1-12

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#452]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

  [DHM-S1-12] On the Dashboard screen: “Safepaths has no affiliation with Google & never shares your data.”  This claim is not completely accurate since one of the key functions of this app is to share the user’s data. 

“… without your consent” should be added, perhaps?

**Comment by summetj** [comment]
Removed from current app.
