### ISSUE TITLE
CONCERN: How will Health Authority Picker scale when we have many of them?  DHM-S1-21

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#458]
-        [DHM-S1-21] When there are many Health Authorities, it is not clear what UX will be to allow me to choose the ones relevant to me.
o   Are they listed alphabetically?
o   How does the app work with a list that is too long to fit on the page?
o   Can I filter for Health Authorities that are local to my area etc.?
o   Can I search for a given Health Authority name?

**Comment by summetj** [comment]
This will eventually be a concern for future us, but I'm going to close the issue as it's more of a specification desire than a problem with the existing codebase. (Hopefully the V2 spec will answer some of your questions above....)  [Auto enroll in Heath Authority based upon location may also make much this a non-issue.]
