### ISSUE TITLE
BUG: Product unclear whether I should have 1 or N Health Authorities - DHM-S1-22

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#459]
[DHM-S1-22] Screen title “Choose health authority” suggests I should just choose one.  “Trusted Sources” + the overall UI design, suggests that I can pick more than one.  Desirable to avoid this ambiguity.

We should decide whether this is 1 or N, and make the whole UI consistent around this.

**Comment by summetj** [comment]
This is resolved by V 1.0.0 app (N HA's allowed).
