### ISSUE TITLE
CONCERN: Security concerns around Health Authorities - DHM-S1-23

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#460]
Various concerns around Health Authorities

I've been told that for a Health Authority to appear in the official list in-app, they just submit a PR to have their entries added to the master YAML file.  I am concerned how the Dev handling this PR is supposed to authenticate that this is a real Health Authority & not a bad actor?

Also concerns where the user enters the URL directly:

 Not clear whether the app will mandate the use of HTTPS for Health Authority URLs, and insist on trusted security certificates.  What happens if the user enters HTTP & the site redirects to HTTPS.  Does that work?  

 There could be a security risk of an attack where users are encouraged to enter a malicious URL in the app.

**Comment by E3V3A** [comment]
The user should be able to enter manually if needed. (Gov'ts has a tendency to shuffle around URLs on short notice and other users may not even have a well established health "authority" that can handle providing this data. Therefore we can imagine NGO's offering these services...

**Comment by summetj** [comment]
User can now enter a HA via URL manually.

The PathCheck organization will police new Health Authorities, this is a policy issue outside of github and this code base.
