### ISSUE TITLE
BUG: slight delay populating Health Authories from list, relative to URL option - DHM-S1-24

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#461]
[DHM-S1-24 - New #461] The 1st time I use the “Add Trusted Source” button, only “Add authority via URL” is visible – the other 2 available entries take a few seconds to populate.

I understand this is because the app has to download a YAML file containing the latest list of Health Authorities.

This gives a slightly unpleasant UX.

Can we:
- predownload the list on app startup?  I note that 2nd & later times all is well.
- or: wait until we have downloaded the list before displaying anything.

**Comment by E3V3A** [comment]
just inform the user what is going on, otherwise they'll think the app crashed.

**Comment by NethravathiPuttraju** [comment]
I can look into this..

**Comment by NethravathiPuttraju** [comment]
I have tested this issue. I found that , when i click on "Add trusted source" all the 3 entries populate once without any delay. May i know in which OS version and device your facing this issue.

**Comment by diarmidmackenzie** [comment]
Yes, I agree at v0.9.4, this is immediate, even on the 1st time after a re-install of the app (which was when I could repro this before).

This appears to be fixed.

**Comment by NethravathiPuttraju** [comment]
Okay.. Then can we close this Issue?
