### ISSUE TITLE
Tidy up available Health Authorities, before going live DHM_URGENT

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#462]
Currently the app has a couple of obviously "test" Health Authorities (available & no real ones.

This has been fine for testing, but not suitable for the app to be live on the app store.

Exactly what the right spec is here is not clear:
- For demo purposes, it's nice to have 1 or 2 sample Health Authorities (even if not real)
- For real users, it's potentially confusing to have these options when they are not meaningful.

Further, if there are no HAs at all it creates an odd UX.  The user will wonder what is the point of the screen.  Is there a bug?

Might be better to have a placeholder on the screen that indicates that HAs are "coming soon" - that will help the user to read the situation.

As I say, not clear exaclty what we need, but I'm pretty confident that the messy couple of test HAs we have today is now what we should have at launch.

**Comment by diarmidmackenzie** [comment]
I believe this should be a priority ahead of plaunching on the App Store.  What we have no looks like a test version of the App, not something production ready.

**Comment by tremblerz** [comment]
The name of authorities come from the json hosted on Safe-places, once we know a valid URL from an authority which will host the files, we can definitely make the change.

**Comment by E3V3A** [comment]
@tremblerz 
Can you be more specific? 

* What *files* are needed?
* What should the files contain?
* What is the link to the safe-places json?
* How can we as locals (from various countries) find and give you the URLs you need?

**Comment by diarmidmackenzie** [comment]
@tremblerz - I think this misses the point.  With the info in the JSON today, the UX is bad - looks like a test app.

I think we should:
- DEFINITELY: remove "TEst Authority" and "Mairie de PAP/MSSP" from the JSON file.  These are not real and it is confusing to users when only these 2 options are offered.
- PROBABLY: Implement some default message when the JSON file is empty so the app displays suitable test like "Health authorities will shortly be available in your region", to help the user interpret the blank display.

**Comment by diarmidmackenzie** [comment]
Spotted another inconsistent terminology.  in the text panel we say "web address", in the menu option we say "URL".  We should pick one term or the other.

"web address" is probably better given target audience is non-technical.

**Comment by penrods** [comment]
I will be removing the Haitian authority that is hard coded (Mairie de Pap).  I'll like to this when I do that PR.

I will look to see if we can refine text, on that page, but I don't think it is a showstopper -- it can be massaged and refined in the next week.

Additionally, the GPS bounding-based "auto-subscribe" system will be here soon which will make this page largely unnecessary for anyone to actively visit unless they have actions already setup for them.

**Comment by penrods** [comment]
#499 removes Haiti
