### ISSUE TITLE
Not possible to install Safe Paths app if Private Kit is installed DHM_URGENT

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#463]
Private Kit app must be uninstalled before installing Safe Paths app.

When installing Safe Paths via APK, there is just a brief "install failed" message.

I'm not sure what the UX will be if installing from Play Stire, but suspect it will also fail with no clear message.

The conflict between the apps won't be clear, hence users unlikely to figure out the issue & resolve themselves,

Can we fix the conflict?  If not, can we put really clear guidance in the Play Store explaining that Private Kit must be uninstalled first before installing Safe Paths?

**Comment by diarmidmackenzie** [comment]
This also affects install of an APK, if eiother Private Kit, or an earlier app version is installed - we should fix this in the docs for testers.

Here: 
https://docs.google.com/document/d/1HN9XkS-C7X0rJUZ5wom9wE8-7gBygHT8PLOEAEFiYOU/edit#

(though permissions mean I now can't see this - is it out of date?)

**Comment by diarmidmackenzie** [comment]
As we look to pushing this onto the App Store, I think this is pretty urgent to resolve (at a minimum documenting the workaround on our App Store page)

I expect there will be a signficiant intersection between people who previously installed Private Kit, and those who want to install Safe Paths.

**Comment by penrods** [comment]
I suspect there isn't a technical solution to this, it will be all about messaging.  Including this on the app description makes sense, for sure -- good idea!

**Comment by kenpugsley** [comment]
A couple of things to reply to ..

> When installing Safe Paths via APK, there is just a brief "install failed" message.

This does not happen to me, though I usually uninstall the previous app before installing from the apk.  Do you see this even if you've uninstalled the app first? 

> Can we fix the conflict? If not, can we put really clear guidance in the Play Store explaining that Private Kit must be uninstalled first before installing Safe Paths?

As of the v0.9.2 version of the app (and going forward), Private Kit no longer needs to be uninstalled in order for COVID Safe Paths to be installed.  They are now completely different apps and will no longer conflict with one another.

**Comment by diarmidmackenzie** [comment]
1st point - no, I only see this when I have not uninstalled the 1st app.  Sorry that was not clear.

2nd point.  OK - I will test this.

**Comment by diarmidmackenzie** [comment]
Hi - I tested installing SafePaths alongside Private Kit.  Basic install & initial setup all works OK, and a skim test of all the function didn't throw up any issues.

I will leave Private Kit installed so that we get a bit more casual test coverage of this combination, but the evidence I have seen so far, combined with your confident assertion that the apps are completely separate and should not conflict, from a design pov, I think we can consider this resolved.

**Comment by kenpugsley** [comment]
closing per @diarmidmackenzie
