### ISSUE TITLE
DEV:  Include platform specific translations in translator workflow

### ISSUE THREAD

**Issue by kenpugsley** [tripleblindmarket/covid-safe-paths#468]
We need to include the platform specific (Android, iOS) translations in the workflow from the translators.  This will help with having the translated app name, descriptions, etc.  

for reference:
- https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription
- https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-102276
- https://hackernoon.com/localize-an-application-name-in-react-native-c36c4b2be7c3

**Comment by kenpugsley** [comment]
@alpita-masurkar @tstirrat - a few more things we need to include in the translations.  @penrods found these links, and we'll need to get them included in the translations and updated in the appropriate files accordingly.

**Comment by alpita-masurkar** [comment]
Ok sounds good... have updated the new translation document to reflect some of these things. Does the App Store/ Playstore description for the app currently auto-translate our English description?

**Comment by kenpugsley** [comment]
Moving this out to the release following v1.0, as there's a certain amount of uncertainty about when to translate the app name (do we do it for all languages, only pictogram based texts, never?), as well as some technical challenges that are not so straightforward, especially on iOS, for doing this in a scalable way.

Once we've implemented a non-manual translation framework, we should be able to get this into the workflow.
