### ISSUE TITLE
CONCERN: Terms of Use hidden away, never seek user consent - DHM-S1-27

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#470]
Terms of Use say "By using that app, you acknowledge you have read and understand this agreement...." etc.

But never at any point did I have to explicitly agree to Terms.  And they are hidden away in a sub-menu under Legal?

How can I agree to the terms by using the app, if the app doesn't make this clear to me?

I'm not an expert in this area, but this seems deeply suspicious to me.  If the terms matter and we need them to be enforceable, then at least in some jurisdictions, I believe we will need explicit user buy-in.

Do we have a Legal expert we can consult on this?

**Comment by E3V3A** [comment]
Nobody read this, just skip it and refer to the same text on the Play store linked webpage. 
(Let's not waste time discussing these kind of things before actually making this work.)

**Comment by harshvitra** [comment]
@diarmidmackenzie @tremblerz 

We do have terms of use on the Legal Page. 
**Under Settings > Legal > Terms of Use**

**Comment by diarmidmackenzie** [comment]
Yes, I agree we do have it in that location,  Maybe I didn't express my concern clearly.

It says "by using this ap you have read these terms etc..."

However a user can make use of the app without even finding these terms.  What I normally see in apps is a flow where you cannot use the app unless you have explicitly consented to the Terms.

I don't have expertise in this area, and happy to defer to someone who does, but my basic understanding is that if you need the user to consent to the terms, you need to ensure that they consent explicitly (e.g. by checking a box that says I have read the Terms & agree to them).

With the current implementation I believe (in some jurisdictions at least), that the law would not recognize the user as having consented to the Terms.

If it's important to us that the user does consent to the Terms, then, I think we need a different flow where the user has to explictly acknowledge and consent to the flows.

As a next step on this, I would suggest that PM take guidance from our Legal specialists.

**Comment by tremblerz** [comment]
Important to defer this one to an expert, but my understanding is that when the User performs on-boarding, they essentially "sign up" and hence should be agreeing to the terms and conditions right there, especially that data is being logged.

**Comment by diarmidmackenzie** [comment]
With the current initial setup flow, there is nothing that I saw as a user that gave me an impression I was "signing up" to any set of Terms.

**Comment by penrods** [comment]
The common behavior with the App stores is that you install at your own will.  No normal application does this, and this application has almost no with outside servers by design.  Placing some arbitrary "Agree to Terms of Use" screen will just discourage use.

**Comment by penrods** [comment]
Unless some provides real reason to require terms in the next couple of days, this should be closed.

**Comment by Ferrumofomega** [comment]
This is closed now due to EULAs.
