### ISSUE TITLE
UX: Software Version & OS details reported on "Legal" page - DHM S1-28

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#471]
Tis just seems odd.

The "About" page would be a much better location surely?  These are not legal details.

**Comment by E3V3A** [comment]
You can implement part of the Signal code, as I suggested in #400.

**Comment by harshvitra** [comment]
Earlier the Legal page was called as Licenses and hence we had these titles over there. 

But now it seems correct to shift them to About page
