### ISSUE TITLE
CONCERN: What analytics do we need from the app to assess its efficacy?  DHM-S1-29

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#472]
Once deployed, I believe we will need some understanding of users' experiences of the app - for example how many of them are being told they have a red status, and how soon after installation?

E.g. if every user gets a red status within minutes of installation, this suggests we are generating too many false positives, and the effectiveness of the app may be deteriorated by "crying wolf".

Another consideration: what if a substantial % of users are never actually entering any Healthcare providers?  Etc.

We need to be careful here, because Privacy is of vital importance.  But some analystics could be increddibly valuable, and help us to help the app create more value.

We should find the right balance, and determine what privacy-respecting analytics we can implement, that would be most valuable.

**Comment by summetj** [comment]
Discussion moved to slack.
