### ISSUE TITLE
Discussion: Improve dev efficiency by removing slack channels

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#476]
When first came here to help, I was suggested to join the slack channel(s). I've since abandoned the slack channels, since they are essentially useless from a development standpoint. There is almost no talking at all about development on the dev channel. So what s up with that?

Second, all channels are being spammed with completely irrelevant chatter and repeated spam posts and nobody is moderating or banning the repeat offenders. 

3rd. Anything interesting at all gets lost in the `dev\null` of the slack history. Never to be found again. 

I therefore suggest we stop using slack and start posting dev relevant discussions right here. Easy to be found, easy to maintain, easy to tag, easy to lock, easy to take action on.

**Comment by summetj** [comment]
Much productive non-developer work is happening on Slack which can not also be moved to GitHub. Having developers on Slack allows communication with other roles in the project. (which is much larger than just the codebase).
