### ISSUE TITLE
FOCUS: Start focus on main objective and make everything else iterative

### ISSUE THREAD

**Issue by E3V3A** [tripleblindmarket/covid-safe-paths#477]
This app has now been around since `6 March`, and as of today, `12 April`, **the app still does nothing at all!**

Since then there are now several dozens of apps that have been working for weeks, already doing contact tracing and infected contact mapping. So why are we not? The answer is very simple. 

The app development is over-engineered and lacking the correct development focus, and without a clear strategy on how to enter the market with usability, as soon as possible. ***KISS*** has been forgotten and hidden under a pile of shit discussions about app names, translations, added libraries, insisting on using Google Maps and having to upload or download Google Location data just to save and plot a few points on map telling the user whether or not: (a) he she should be worried of having been infected or (b) having been infected and wanting to tell the world where they were in the last 2 weeks, before. All while the development versions & documents, discussions and implementation plan is hidden away in obscure and very hard to find places, and when found, already outdated. 

* The `close proximity BT tracing` was added week+ ago, but **was disabled for unknown reasons**. The suggestions of ensuring reliable contact points have been mostly ignored. (e.g. #264). 
* The `map functionality` **was removed for unknown reasons**, 8 days ago. (See; #347).

As someone stated in another forum:
> There is much more to say about this, but that project has been *funded, supported* and *internationally recognized*, but I honestly (and sadly) don't think it is going to get off the ground before the US peak is over, unless there is a radical change of mindset of the main driving personalities in that project, putting functional usability first. Nobody give a shit about privacy if their life is at stake. 

Github works great for effective collaborative development, if you know how to use it!

**Comment by summetj** [comment]
I agree that more rapid progress is desirable but do not feel that this issue report is the appropriate place to advocate on these issues.
