### ISSUE TITLE
Problems with Italian Translation

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#483]
I'm not a native Italian speaker (actually I'm not even a very good Italian speaker), so could well have missed some things.

I'm only raising things I am certain are bugs.

Opening screen: Language is "Italian" (i.e. in English), should be "Italiano"
Next screen: "Knowledge is power." still in English.  "Next" button still in English.
Next screen: Again "Next" button still in English.
Version info on Legal screen says "Version: 0.9.2".  Italian would be "Versione: 0.9.2"
"Storico delle esposioni" screen (exposure history) - lower down the page "What does this mean?" all this text is still in English.
On Dashboard: "non condivide mai I tuoi dati"   "I" should not be capitalized - should be "i"
Ultime novita (latest news): these sample pages are still in English.  I'm hoping these are going to be removed anyway, in which case not an issue.

"Selezona le autorita santitarie"
- 2 issues with text overflowing available space: in top title bar & also in the 1st text box.

Some bits that I think are dubious, but would need checking with a native Italian speaker.  Maybe they are OK.

"Dashboard" - isn't there a better Italian word?
"Finisci il Setup" - elsewhere we have used impostazione.  Why "Setup" now?

**Comment by diarmidmackenzie** [comment]
![Screenshot_20200412-225659](https://user-images.githubusercontent.com/16045703/79080173-cd462b80-7d13-11ea-8994-733c4fe2cdcc.png)
![Screenshot_20200412-230223](https://user-images.githubusercontent.com/16045703/79080177-d20adf80-7d13-11ea-9e0e-0a2a218e5aad.png)
![Screenshot_20200412-230200](https://user-images.githubusercontent.com/16045703/79080178-d2a37600-7d13-11ea-9dcd-e7ee342d8192.png)
![Screenshot_20200412-231148](https://user-images.githubusercontent.com/16045703/79080182-d6cf9380-7d13-11ea-8906-bf8e907864c8.png)
![Screenshot_20200412-225642](https://user-images.githubusercontent.com/16045703/79080183-d7682a00-7d13-11ea-9c3d-81daa6039c16.png)
![Screenshot_20200412-224935](https://user-images.githubusercontent.com/16045703/79080184-d800c080-7d13-11ea-8174-fabcf7a3d96b.png)

**Comment by kenpugsley** [comment]
Assigning to @alpita-masurkar

**Comment by andreanuzzo** [comment]
I can answer since I have made the translation:
```
Opening screen: Language is "Italian" (i.e. in English), should be "Italiano"```

The file I translated does not have a key:value pair for that field. So it needs to be changed in the default file. 

```Next screen: "Knowledge is power." still in English. "Next" button still in English.
Next screen: Again "Next" button still in English.```

We don't usually translate those anywhere, people are pretty confident with "Next". Knowledge is power does not translate to an equally powerful sentence in Italian, so I left it as is.

```Version info on Legal screen says "Version: 0.9.2". Italian would be "Versione: 0.9.2"
"Storico delle esposioni" screen (exposure history) - lower down the page "What does this mean?" all this text is still in English.```

Again, no key:value pair for those

```On Dashboard: "non condivide mai I tuoi dati" "I" should not be capitalized - should be "i"```

Damn autocorrect!

```Ultime novita (latest news): these sample pages are still in English. I'm hoping these are going to be removed anyway, in which case not an issue.```

They are pointing at a default web page. So, waiting for them to be updated

```
"Selezona le autorita santitarie"

2 issues with text overflowing available space: in top title bar & also in the 1st text box.
Some bits that I think are dubious, but would need checking with a native Italian speaker. Maybe they are OK.```

Yeah, not sure if adding a `\n` would help in the title bar, but we could do in the text box... 

```"Dashboard" - isn't there a better Italian word?
"Finisci il Setup" - elsewhere we have used impostazione. Why "Setup" now?```

`Impostazioni` usually defines settings. `Setup` is commonly used in Italian as well, as "setting things up". No problem to change that if needed, but it is less common. 

Thanks for checking @diarmidmackenzie. @alpita-masurkar probably could push those changes.

**Comment by alpita-masurkar** [comment]
@diarmidmackenzie thank you for reviewing these and bringing this up. @andreanuzzo thank you for going through these. Will make these changes.

**Comment by alpita-masurkar** [comment]
This issue is linked to a PR. The PR is ready with the requested review changes. It is on a hold right now. Have a look, if everything looks okay, it can be merged and this issue can be closed.
