### ISSUE TITLE
CONCERN: Text on 2-week exposure page.  How do we get it right for a given context on the ground?

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#486]
v0.9.2 has opened up the 2-week exposure profile page.

As far as I can tell #430 is still not fixed, so we can't get anything interesting, but we see a nice (empty) timeline, some reassuring text and some advice.

![Screenshot_20200412-232856](https://user-images.githubusercontent.com/16045703/79080533-01bae700-7d16-11ea-80e5-1d4a65d811c1.png)

So far, this all looks pretty good.  My main concern was when I got to the end and read "If you have no symptoms but still would like to be tested you can go to your nearest testing site".

![Screenshot_20200412-232902](https://user-images.githubusercontent.com/16045703/79080529-fff12380-7d15-11ea-849e-48106877b61e.png)

My worry is that this (and perhaps some of the other guidance) is going to depend hugely on the reality on the ground in whichever country I happen to be in.

The advice in Italy or the UK today is absolutely not that people without symptoms can go to their nearest testing site & request a test.  Tests are only available to people with symptoms, and typically only when they are hospitalized.

This app is in a position of trust, and we need to provide accurate, localized information.

How we do that is hard, but it probably can't be achieved with fixed text encoded in the app.  We need to provide accurate text, regardless of whether the user has app updates enabled etc.  This means that text probably needs to be hosted on a server somewhere and loaded in by the app, rather than being baked into the app.

We also then need to think about how we make sure that that server data serves up location-appropriate text, and that it's kept up-to-date with local polcies & local reality.

Not my intention to design a solution here, but just to try to offer a vision of what a "fix" might look like.

I don't think this is a must fix for basic demos etc., but before the app is really used in anger in the field, we'll need to do something here, I think.

**Comment by Cimbali** [comment]
At the very lest the text should say « consult your local authorities on whether you should get tested », but I agree localizing the app is more work than just translating it. See also a couple of points I raised in #490

**Comment by penrods** [comment]
This is part of a forthcoming change to the Healthcare Authorities publisher.  It will include a link for "What Do I Do Now?" from that page.

**Comment by summetj** [comment]
Resolved in released app.  Each Health Authority will be responsible for this information.
