### ISSUE TITLE
BUG: Incorrect language options offered on Install

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#487]
On install, I am offered the following languages:
- English
- Kreyol ayisyen
- Italian

Ali's test document says I should have a full list of 16 languages.

I thought this behaviour that I was seeing might be a combination of:
- me having my phone set up with dual English & Italian languages
- something left hardcoded in the app relating to Haitian Creaole (plausible since there is some other Haiti stuff stilll hardcoded).

HOWEVER it seems that's NOT what;s going on:
-  I tried adding Francais as a language on my phone.  Even after adding it (and for a further test, even after making it the default language), Francais was not available as a language option, and the interface stayed in English.
- I then removed Italian from my pbone.  Even after removing it, it was still available as an option.

My next hypothesis is that the 3 languages, Engliah, Italian & Kreyol ayisyen are always offered, and no other languages are ever offered.

If so that's 13 languages still missing vs. what's in the test spec.

Maybe this comes down to us needing:
https://github.com/tripleblindmarket/covid-safe-paths/issues/474

**Comment by kenpugsley** [comment]
Looks like we have a gap here is communication.  The most recent UI rework (which converted the app from Private Kit to COVID Safe Paths) caused us to have to start again on translations, and those translations are only now starting to come back in.  @alpita-masurkar is coordinating that effort.

The release tracking spreadsheet is tracking the languages as they are added: https://docs.google.com/spreadsheets/d/1QGVJ-JX6_ah3-u3VL8bskO0HxaXd1A2SlLBgoH32AUU/edit#gid=1780391290 .

As of the current beta (v0.9.2) there are indeed only 3 languages supported (English, Haitian Creole, Italian), and as far I know we've not had independent validation on any of them yet.  So the app is currently working as expected, but our process for communicating expectations leaves something to be desired.

I'm going to close this issue as the app is technically working as expected.  The action item here will be to be more clear on the translations supported as each new beta drop is produced.
