### ISSUE TITLE
Consistency of naming, and thoughts about trademarking and brand protection

### ISSUE THREAD

**Issue by KathyReid** [tripleblindmarket/covid-safe-paths#492]
Firstly, a huge thanks to the team for your incredible efforts in getting this off the ground. 

These thoughts came out of Issue #484  - where we are discussing the SafePaths brand name to make it consistent throughout the entire product. There are a few additional things the team may wish to consider; 

* The domain `safepaths.org` is parked by GoDaddy. Should it be registered and delegated back to MIT as a brand protection mechanism? (`whois` output follows below). 

* Should the implementation teams in different countries try and register `safepaths.org.ccTLD` in their jurisdiction, for example `safepaths.org.au` in Australia? (`whois` output follows below). The reason here is that I can see unscrupulous / malicious actors trying to direct people away from legitimate sites. It might also be worth registering `safepaths.dev` and `safepaths.ai`, again for the same reasons. 

* Should "SafePaths" be copyrighted or trademarked somehow by the MIT team? I don't know if this has already occurred, but it might be a step to consider about now. 

Kind regards, 
Kathy 

## Whois output for `safepaths.org` 

```
kathyreid@~$ whois safepaths.org
Domain Name: SAFEPATHS.ORG
Registry Domain ID: D402200000008477025-LROR
Registrar WHOIS Server: whois.godaddy.com
Registrar URL: http://www.whois.godaddy.com
Updated Date: 2019-01-28T03:53:12Z
Creation Date: 2018-11-28T19:58:24Z
Registry Expiry Date: 2020-11-28T19:58:24Z
Registrar Registration Expiration Date:
Registrar: GoDaddy.com, LLC
Registrar IANA ID: 146
Registrar Abuse Contact Email: abuse@godaddy.com
Registrar Abuse Contact Phone: +1.4806242505
Reseller:
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Registrant Organization:
Registrant State/Province: California
Registrant Country: US
Name Server: NS67.DOMAINCONTROL.COM
Name Server: NS68.DOMAINCONTROL.COM
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form https://www.icann.org/wicf/)
>>> Last update of WHOIS database: 2020-04-13T12:21:52Z <<<
```

## Whois output for `safepaths.org.au`

```
kathyreid@~$ whois safepaths.org.au
NOT FOUND
>>> Last update of WHOIS database: 2020-04-13T12:22:24Z <<<
```

**Comment by summetj** [comment]
Moving to slack for policy/communications discussion.
