### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by timswagwalker** [tripleblindmarket/covid-safe-paths#494]
I'm on MacOS, trying to set up the environment for iOS.

When trying to set up the development environment, I constantly get the following error message:
```
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
/Users/tanaynistala/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing: Unknown `--is-lightweight' option
Try `/Users/tanaynistala/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/tanaynistala/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-1f3da':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
Which follows a large snippet of code (see the attached image). Maybe I'm setting it up wrong, so could I get some clarification on where to run each of the setup commands (`./dev_setup.sh`, `yarn install` and `yarn install:pod`)
<img width="1136" alt="Screen Shot 2020-04-13 at 7 39 54 PM" src="https://user-images.githubusercontent.com/24990666/79126947-8eb97b00-7dbe-11ea-8173-d3c7e5925936.png">

**Comment by ismail00b** [comment]
you have to run this command and the issue will be solved 
sudo xcode-select --switch /Applications/Xcode.app

**Comment by summetj** [comment]
timswagwalker please close the issue if the above resolved it for you.

**Comment by timswagwalker** [comment]
That worked! Thanks
