### ISSUE TITLE
Missing Key in the en.json file?

### ISSUE THREAD

**Issue by alpita-masurkar** [tripleblindmarket/covid-safe-paths#495]
This was brought up by @diarmidmackenzie in an issue in another case https://github.com/tripleblindmarket/covid-safe-paths/issues/483

On the Exposure History page, there is some English text that goes like this:
What does this mean? Individuals who don't exhibit symptoms can sometimes still carry the infection and infect others. Being careful about...

This text is not getting translated as it is not included in the en.json file. Is there a missing key for this?

**Comment by kenpugsley** [comment]
Good catch.  Looks like we have a couple of untokenized strings.  

For dev reference:  Notifications.js Lines 219-231
