### ISSUE TITLE
Update Dutch Translation

### ISSUE THREAD

**Issue by danoszz** [tripleblindmarket/covid-safe-paths#536]
## Description

Update the Dutch translation to the new [locale format](https://github.com/tripleblindmarket/covid-safe-paths/tree/develop/app/locales).

## Motivation

In PR https://github.com/tripleblindmarket/covid-safe-paths/pull/310, a redo of the Dutch translations was [requested](https://github.com/tripleblindmarket/covid-safe-paths/pull/310#issuecomment-611904883). 

## Assignment

I will handle the translation, restructuring and implementation, based earlier translations done by the community.  Any updates will be posted in this issue.

**Comment by alpita-masurkar** [comment]
Hi @danoszz, how is this pr progressing? do you have any new updates on this?

**Comment by danoszz** [comment]
@alpita-masurkar on it right now! Making a PR any moment. It took some extra time because the translation was read by a couple of other native Dutch speakers in various age categories.

**Comment by alpita-masurkar** [comment]
that's awesome @danoszz will have a look at the PR!

**Comment by danoszz** [comment]
@alpita-masurkar I see it fails on the recently added translations. Let me quickly add those and make a new PR. 

```json
{
  "history": {
    "no_exposure": "",
    "possible_exposure": "",
    "possible_exposure_para": "",
    "what_does_this_mean": "",
    "what_does_this_mean_para": "",
    "what_if_no_symptoms": "",
    "what_if_no_symptoms_para": ""
  },
```
