### ISSUE TITLE
"Exposure history" seems confusing when there is no data populated

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#547]
## Version

- Android 9
- Motorola G7 power

## Steps to reproduce

Install app.  Set up a Health Authority to point to my location.

Like this, but with my lat & long:
http://diarmidmackenzie.pythonanywhere.com/infection-data?longitude=1&latitude=2

Navigate to Exposure History tab

![image](https://user-images.githubusercontent.com/16045703/79551492-037c0600-809a-11ea-9e2c-cfef1c3fcbb9.png)

All days are blank (no data).  That's expected.

But notes are confusing to me:

"No known contact".  OK.

But then the "what does this mean?" notes say it is possible that I may have been in contact with someone who was diagnosed.

Well, that's true, in the sense that whatever the data on my phone says it's always *possible* I had such contact (we don't claim zero false negatives!).

But in the context of NO matches, the text is confusing.

Interestingly, when I close the app and re-open, I find the last 14 days all green.  What?

![image](https://user-images.githubusercontent.com/16045703/79615486-33abbf00-8103-11ea-9b34-94f13591d8aa.png)

We still have no data from that period (the HA is providing data, but my phone has no data - Google Data import is removed in this version ("comign soon").  So how can it be deciding that those days are "green" when there is no data for those days?.

Again, we still have the confusing

"No known contact" followed by the warning that "it is possible that I may have been in contact...."

So I think probably 2 bugs here, but I'd appreciate someone take a look before I spin up another issue.  I am puzzled by the UX and may be missing something.

- micmatch in message between "no known contact" and "it is possible that...."
- on restarting the app, I get 14 days positive data, when I should be getting days reported with no data.

FYI, the 14d does not come from the mock HA.  The mock HA URL will, by default, serve just 1 day of data.

**Comment by diarmidmackenzie** [comment]
Further note, although I did set up an A by URL, 

The access logs logs at the python annywhere server show that the app is still not hitting the server.

Therefore #430 still broken, and the app behaviour is totally unrelated to any data that the HA URL might be serving.

**Comment by anigasan** [comment]
I don't see any dates in my installed app:
![Screenshot_20200417-121217_COVID Safe Paths](https://user-images.githubusercontent.com/29756847/79590852-ad14c480-80a5-11ea-90c2-aa4770529476.jpg)

**Comment by diarmidmackenzie** [comment]
Are you running v0.9.4?
Did you add a Health Authority?

With ,me that was enough to get the calendar view.

Then after adding the HA, restart the app, and that produced the 14 green days.

**Comment by anigasan** [comment]
Yes, it is v0.9.4 and also added two HAs (Example and Mairie de PAP/MSSP)!

It tried restarting the app and also tried rebooting the device. Still not getting calendar view  :)

**Comment by summetj** [comment]
v 1.0.0 fixes these issues.
