### ISSUE TITLE
Is it COVID19 or COVID-19?

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#548]
Seen on v0.9.4, with Android 9 on Moto G7.

WIthin the space of a single screen, we refer to the disease by 2 different names:

COVID19 and COVID-19.

Please can we be consistent on all screens throughout the app?  (COVID-19, with the dash, is what I'd expect, but happy with either as long as we are consistent).

-->
![image](https://user-images.githubusercontent.com/16045703/79552163-f3185b00-809a-11ea-8d71-079481bd388c.png)

**Comment by NethravathiPuttraju** [comment]
I can make it consistent on all the screens .
