### ISSUE TITLE
Update text on Settings screen/button

### ISSUE THREAD

**Issue by meekg33k** [tripleblindmarket/covid-safe-paths#561]
## Version

- Type of phone: Android / iPhone

## Current Text

![text-change-1](https://user-images.githubusercontent.com/14355147/79624860-96886080-80d9-11ea-8dba-c4a459995a0e.png)

![text-change-2](https://user-images.githubusercontent.com/14355147/79624862-9b4d1480-80d9-11ea-8dd1-c7d0b0c9ef38.png)

## Expected Change
- Update text on screen from "_to be informed of exposures you need to subscribe..._" to "_to be informed of future location matches you need to.._"

- Update button text from "_Add Trusted source_" to "_Add Data source_"

**Comment by penrods** [comment]
The terminology is sometimes quirky right now, but there are reasons.  This will be modified based on requirements of the various stores and healthcare authorities as we negotiate that processs.

**Comment by meekg33k** [comment]
@penrods, this was a requirement from a board member. Sam Zimmerman will have more details, you might want to check in with him before marking this as closed.
