### ISSUE TITLE
Can't import my google location history

### ISSUE THREAD

**Issue by AdamLeonSmith** [tripleblindmarket/covid-safe-paths#570]
## Version

- Type of phone: Android
- OS Version: Andorid 10
- Model: e.g.  Pixel 3a

## Steps to reproduce
Download google location history
Close app
Reopen app

## Expected Behavior
Location history is imported

## Actual Behaviour
Exception is visible on primary app scren in yellow.  Exception is in full below from logcatW ReactNativeJS: Can't open url: intent:#Intent;package=com.google.android.gms;action=com.google.android.gms.accountsettings.action.BROWSE_SETTINGS;S.extra.fallbackUrl=https%3A%2F%2Fmyaccount.google.com%2Fsecurity-checkup%3Fcontinue%3Dhttps%3A%2F%2Fmyaccount.google.com%2F%3Fpli%253D1;S.browser_fallback_url=https%3A%2F%2Fmyaccount.google.com%2Fsecurity-checkup%3Fcontinue%3Dhttps%3A%2F%2Fmyaccount.google.com%2F%3Fpli%253D1;i.extra.screenId=400;B.extra.fallbackAuth=true;S.extra.accountName=redacted%40gmail.com;end
:

**Comment by AdamLeonSmith** [comment]
Note that my google location history contains more than 1.7 million data points going back years...  This may be related.

**Comment by danoszz** [comment]
@AdamLeonSmith thanks for addressing this issue. Did you export your data with Google Takeout and the following settings?

 1. Delivery method: "Add to Drive" 
2. Frequency: "Export once" 
3. File type & size: ".zip" and "1GB"

**Comment by danoszz** [comment]
After a chat on with @AdamLeonSmith to breakdown the problem, I could recreate this issue on iOS V0.5.19. 

Here's the reproduction video:

Screenshot of the error | Steps to get this error
--- | ---
![IMG_4C31F748D9CB-1](https://user-images.githubusercontent.com/14123926/79782401-4f9ba480-833f-11ea-9a0a-a7350dde3812.jpeg) | ![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/14123926/79782393-48749680-833f-11ea-8f77-9b75b32a7e0a.gif)

**Comment by AdamLeonSmith** [comment]
I just tested this on develop (2aa0dea277d63e4f29b402702f50c8a598660946) and it works fine!
