### ISSUE TITLE
Text cropped on top for all 3 intro screens on android app

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#606]
## Version : 0.9.5

- Type of phone: Android
- OS Version: 9
- Model: e.g. Moto G6 plus

## Steps to reproduce

- Click on the app icon and move to the intro screens.

- All three intro screens have the text cropped on top.

**Comment by ilonadynska** [comment]
This issue applies also on other localisation (e.g. Italian, Polish) so seems replicable on all.
Tested on:
- Samsung A50 - 9.0
- Samsung S10 - 10.0

![Screenshot_20200422-005233_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79922887-b353c980-8434-11ea-9374-758b312dabd0.jpg)
![Screenshot_20200421-235920_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79922956-e4cc9500-8434-11ea-80d3-bda221bd4e57.jpg)

**Comment by saranyaharidas** [comment]
will check this one
