### ISSUE TITLE
Green icon on the "No known contact " screen

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#607]
## 0.9.5

- Type of phone: Android
- OS Version: 9
- Model: e.g. Moto g6 plus

## Steps to reproduce

1. Click on the installed safe paths app.
2. Get started and give location access
3. Once the user lands on "No known contacts" screen

*## Expected Behavior**
Grey icon to be displayed

actual behaviour:
Green icon is displayed. Attaching screenshot for reference.

![greenicon](https://user-images.githubusercontent.com/63336927/79858165-9b585780-83ec-11ea-837e-d576de2f9daa.jpeg)

**Comment by ArchanaNair** [comment]
Will check this

**Comment by ArchanaNair** [comment]
@vedhakannan @summetj As per MVP, the current UI behaviour is correct for 'No known contact'.  Please confirm if any changes required.

**Comment by ShreyaaSahu** [comment]
@ArchanaNair In MVP there is a dialog box stating that it should be grey instead of green 
![Screenshot (5599)](https://user-images.githubusercontent.com/64080646/80181217-09399480-8622-11ea-989e-a2d4d1c920d8.png)
.

**Comment by Patrick-Erichsen** [comment]
Closing for now as this matches the stated MVP docs. Worth keeping in mind as a data point for UX though.

**Comment by driedgrape** [comment]
The MVP doc is out-out-date compared to the current release. Please see the 1.0.1 prototype for the latest reference: https://www.figma.com/proto/aOz2hCg6agulId3mGCQIv8/Safe-Paths-Version-1.0.1?node-id=1228%3A70&viewport=-2227%2C-928%2C0.47152677178382874&scaling=scale-down.

Based on the most up-to-date specs, the expected response is "No known contact" with a green indicator.

"home_no_contact_header": "No known contact",
"home_no_contact_subtext": "Based on available data you haven’t been near anyone reported positive for COVID-19.
