### ISSUE TITLE
Red icon appears for a second before load of "No known contacts" page

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#608]
## Version 0.9.5

- Type of phone: Android 
- OS Version: 9
- Model: e.g. Moto g6 plus

## Steps to reproduce
Click on the installed safe paths app.
Get started and give location access
Once the user lands on "No known contacts" screen

## Expected Behavior
Once the user lands on "No known contacts" screen

Actual behavior
Flikker of page appears with a red icon , for a second

**Comment by denispapakul** [comment]
I can look into this issue

**Comment by arvind-source** [comment]
Red Icon Flicker Issue on "No known contacts" page issue resolved

**Comment by summetj** [comment]
@denispapakul - Can you take a look at the bigger picture issues raised in the pull request?

**Comment by summetj** [comment]
> Red Icon Flicker Issue on "No known contacts" page issue resolved

Should we close this issue and the pending pull request? (closed by other fixes?)

**Comment by arvind-source** [comment]
Yes bcz I have tested on below configuration it is having no issues now red icon.
Type of phone: Android
OS Version: 9

**Comment by tstirrat** [comment]
This was fixed in the location refactor #749
