### ISSUE TITLE
Text cropped on top for all 3 intro screens on IOS app

### ISSUE THREAD

**Issue by Shreya050695** [tripleblindmarket/covid-safe-paths#610]
![IMG-4517](https://user-images.githubusercontent.com/64080646/79865601-0a3bad80-83f9-11ea-9185-8f3a5da50bcf.PNG)
![IMG-4518](https://user-images.githubusercontent.com/64080646/79865605-0d369e00-83f9-11ea-92dc-ccc532489f33.PNG)
![IMG-4519](https://user-images.githubusercontent.com/64080646/79865609-0f98f800-83f9-11ea-81f8-32dd8a0e388c.PNG)

## Version 0.9.5

Type of phone: IOS
IOS Version: 13.3
Model: e.g. iPhone XR

##Step to reproduce

1. Click on the app icon and move to the intro screens.
2. All three intro screens have the text cropped on top.

**Comment by alpita-masurkar** [comment]
similar to #606 ?

**Comment by saranyaharidas** [comment]
@alpita-masurkar : looks like this and #606 are similar.  check the below PR
[PR](https://github.com/tripleblindmarket/covid-safe-paths/pull/627)
