### ISSUE TITLE
new button seen below the "visit google take out" button on "import locations page"

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#613]
![Motog6plus](https://user-images.githubusercontent.com/63336927/79898186-7386e500-8428-11ea-8315-f32057414762.jpeg)

## Version

- Type of phone: Android 
- OS Version: 9
- Model: Moto g6 plus

## Steps to reproduce
On click of Google maps -> "Import past locations"

Attaching screen shot for reference (5.7 inch screen size)

Actual : 
Extra button seen below "visit google take out" but unable to scroll down.

**Comment by diarmidmackenzie** [comment]
I have a G7 - I can see the IMPORT LOCATIONS button below VISIT GOOGLE TAKEOUT, enough to clic on, but it still goes beyond the bottom of the screen.

**Comment by NethravathiPuttraju** [comment]
I have tested this in MotoG version 5.1 and also in Samsung A50. Since the scrollview is added for the screen  I am able to scroll the screen and i can see both the buttons. @vedhakannan  Scrollview not working for this screen, in the device that you are testing?

**Comment by tstirrat** [comment]
Fixed in #640
