### ISSUE TITLE
[Home] Misplaced ripple effect 

### ISSUE THREAD

**Issue by ilonadynska** [tripleblindmarket/covid-safe-paths#617]
## Version - 0.9.5

- Type of phone: Android 
- OS Version: 9.0, 10.0
- Model: Samsung A50, Samsung Galaxy S10

## Steps to reproduce

1. Complete onboarding procedure
2. Reach the home

## Expected Behavior

The ripple effect should be centered in the center of the icon.
Instead it results a bit shifted down.
The issue applies to each language.

![Screenshot_20200422-002152_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79923831-b2bc3280-8436-11ea-89ce-3658d97f0f51.jpg)

**Comment by darkerthanblackoff** [comment]
Also appears on XIAOMI MI 8 Lite, so it's not device specific problem.

**Comment by ilonadynska** [comment]
Seems instead the Motorola G6 Plus works fine looking at the screen in #607

**Comment by diarmidmackenzie** [comment]
Moto G7 has an off center ripple too.  The G7 has a longer screen than the G6.

**Comment by vestial** [comment]
I'll take a look into this

**Comment by vestial** [comment]
Hi, I currently don't see any issue with the ripples on all devices mentioned above in the new `develop` branch. Can you guys confirm it?

**Comment by summetj** [comment]
No longer an issue,closing.
