### ISSUE TITLE
[Exposure history] - Legend below calender not fully visible

### ISSUE THREAD

**Issue by ilonadynska** [tripleblindmarket/covid-safe-paths#621]
## Version 0.9.5

- Type of phone: Android 
- OS Version: 9.0, 10.0
- Model: Samsung A50, Samsung Galaxy S10

## Steps to reproduce
1. From home tap the right top setting button
2. Tap on Exposure history

Affected languages:

- Polish
- Italian
- Indonesian
- Dutch
- Slovak

## Expected Behavior
The legend below the calendar should be fully readable.

![Screenshot_20200422-000606_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79926558-85bf4e00-843d-11ea-9a1e-f9dd88358798.jpg)

**Comment by denispapakul** [comment]
I'll look into this issue

**Comment by tstirrat** [comment]
Fixed in #628
