### ISSUE TITLE
App content isn't coming in desired language which was selected in the dropdown 

### ISSUE THREAD

**Issue by ShreyaaSahu** [tripleblindmarket/covid-safe-paths#622]
## Version

- Type of phone: iPhone
- OS Version: 13.3
- Model: iPhone XR

-App Version 0.9.5

## Steps to reproduce

1.Launch the App for first time 
2. Screen  open "The way back to normal starts here"
3.Tap on "English"
4. Select any other language . e.g. Espanol
5.Now again tap on "Espanol" (Language dropdown)
6.Select English again.
7. Close the app without clicking on "Get Started"
8.Now relaunch the App
9.Screens open "The way back to normal starts here" with "English " language as selected language
10.Click on "Get Started"
11.Next screens and App content are displaying in Other language.

![IMG-4525](https://user-images.githubusercontent.com/64080646/79954177-95b94b00-849a-11ea-8527-a9db96dda6e7.PNG)
![IMG-4526](https://user-images.githubusercontent.com/64080646/79954638-3a3b8d00-849b-11ea-9f41-a64459345812.PNG)
![IMG-4527](https://user-images.githubusercontent.com/64080646/79954259-b8e3fa80-849a-11ea-97de-0ef17d9c5b99.PNG)
![IMG-4528](https://user-images.githubusercontent.com/64080646/79954277-bed9db80-849a-11ea-9386-aa338c1fca6c.PNG)
![IMG-4529](https://user-images.githubusercontent.com/64080646/79954309-ca2d0700-849a-11ea-9c57-6bb5c6e9aad9.PNG)
![IMG-4530](https://user-images.githubusercontent.com/64080646/79954336-d44f0580-849a-11ea-9377-9b8d6c100bbc.PNG)
![IMG-4532](https://user-images.githubusercontent.com/64080646/79954424-efba1080-849a-11ea-98d7-cef64ca1cacc.PNG)
![IMG-4533](https://user-images.githubusercontent.com/64080646/79954468-fcd6ff80-849a-11ea-9793-fcde715530e8.PNG)
![IMG-4534](https://user-images.githubusercontent.com/64080646/79954471-fea0c300-849a-11ea-8c4a-d3a519ee40dd.PNG)

**Comment by Niniya173** [comment]
Same issue is identified when I tested in IOS, for me in the first page only 2 different languages are seen, when language was changed from English to some other and back to English.

![image](https://user-images.githubusercontent.com/64129755/79957230-e29f2080-849e-11ea-8238-a62ed8e36795.png)

**Comment by tstirrat** [comment]
Fixed in #649
