### ISSUE TITLE
Language selection shows default language on return to app

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#623]
## Version

- Type of phone: Android
- OS Version: 9
- Model: Moto g6 plus

## Steps to reproduce

- Load app change language to italiano
- quit app before getting onboarded

## Expected Behavior
On return back the language selected should should show italiano and also page should be in italiano.

Actual 
- Language selected shows as english but the page appears in italiano

![Languageselector](https://user-images.githubusercontent.com/63336927/79957024-9d7aee80-849e-11ea-97b6-f8453092dbfc.jpeg)

**Comment by arvind-source** [comment]
I can start looking at this issue.

**Comment by aartiverma1** [comment]
Assign this to me.

**Comment by tstirrat** [comment]
Fixed in #649
