### ISSUE TITLE
Missing documentation for adding background-geolocation environment variable 

### ISSUE THREAD

**Issue by samikhalildev** [tripleblindmarket/covid-safe-paths#629]
## Version

- Type of phone: Android 

## Steps to reproduce
I realised this was missing in the documentation when I was trying to run the application for android.

### Configure background-geolocation SDK
Create a file named ```local.properties``` in /android directory with an environment variable pointing to the android SDK:
* For windows add: ```sdk.dir = C:\\Users\\USERNAME\\AppData\\Local\\Android\\sdk```
* For macOS add: ```sdk.dir = /Users/USERNAME/Library/Android/sdk```
* For linux add: ```sdk.dir = /home/USERNAME/Android/Sdk```

**Comment by summetj** [comment]
Linked to #630, closed.
