### ISSUE TITLE
Issue with Italian translation

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#632]
Tested on 
Sony Xperia XZ1 - Android 9.0, Samsung Galaxy S4 - Android 10.0, Sony Xperia X - Android 9.0

## Steps to reproduce
After clicking "incominciamo", the sentence "knowledge is power" appears. It should be translated in Italian (to maintain consistency with the other pages). 

The expected translation is: sapere è potere

https://www.jotform.com/uploads/AppQuality/201096241235345/4632140126817427183/20200420_172437.jpg

**Comment by matteocrippa** [comment]
@vedhakannan will take care of that in an upcoming PR

**Comment by alpita-masurkar** [comment]
@matteocrippa just following up, do you know if this issue has been addressed yet?
