### ISSUE TITLE
Exposure history :No Data and No known texts moving out of the screen in italian

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#634]
Issue 1 : No Data and No known texts moving out of the screen in italian

## Version

Galaxy   Note 10+ - Android 10 and Moto g6 plus

Actual : 
No Data and No known words  in exposure history ,moving out of the screen in italian

In   "storico delle esposizioni" section (exposure history): the legend (the words:no exposure, possible exposure, nessun dato) below the calendar is too large, the words almost reach the edges of the screen.

https://www.jotform.com/uploads/AppQuality/201096241235345/4632140126817427183/Safe   Paths - calendar .jpg

Issue 2 : in Exposure history : 

 there's a calendar with every day of the month.

In this section there are 2 problem: 1)  why doesn't the month start from the first day?
2) the label of the month (see   screenshot) says "marzo/aprile". What does it mean?

Expected : to show just one whole month data.

**Comment by matteocrippa** [comment]
duplicate of #621

**Comment by vedhakannan** [comment]
Closing this since its duplicate of 621
