### ISSUE TITLE
Typos in italian language translation

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#635]
Error on   the transcription of the phrase "don't worry" in italian language.   You have written

Actual :
non preoccupati 

 Expected : "non pre occuparti". 

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-26-35.jpg

Issue 2 in translation : 
 all subtitles are different from each other (e.g. some have the dot at the end and others don't)

Expected : all of them should be uniform.

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-40-43.jpg   

https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-40-53.jpg   
https://www.jotform.com/uploads/AppQuality/201096241235345/4631995838174799450/photo_2020-04-20_15-41-17.jpg

**Comment by matteocrippa** [comment]
@vedhakannan It's correct `non preoccuparti` that literally means `don't worry`.
The suggested fix is wrong becase in italians means something like `don't start to take care of`.

**Comment by matteocrippa** [comment]
Fixed in the meanwhile the formatting of the title/subtitle with #626
