### ISSUE TITLE
Below mentioned words not been translated to Italian 

### ISSUE THREAD

**Issue by vedhakannan** [tripleblindmarket/covid-safe-paths#636]
Below mentioned words not been translated to Italian
## Version : 0.9.5

- Type of phone: Android
- OS Version: 9 
- Model: Moto g6 plus

## Steps to reproduce

Below mentioned texts are not translated to italian : 
Dashboard   > "Ultime novità" section > autorità "sanitarie"   and not "sanitare"
 
Dashboard > Informazioni   > Missione section > "l'interazione" and not   "l'intereazione"
 
Dashboard > Legale > all  text is in English instead Italian
 
Dashboard > Legale >   Termini per l'utilizzo > all text is in English instead of Italian
 

https://www.jotform.com/uploads/AppQuality/201096241235345/4631877657423941871/InkedScreenshot_20200420-120339_COVID   Safe Paths_LI.jpg
 
https://www.jotform.com/uploads/AppQuality/201096241235345/4631877657423941871/InkedScreenshot_20200420-120413_COVID   Safe Paths_LI.jpg
 
https://www.jotform.com/uploads/AppQuality/201096241235345/4631877657423941871/InkedScreenshot_20200420-120442_COVID   Safe Paths_LI.jpg
 
https://www.jotform.com/uploads/AppQuality/201096241235345/4631877657423941871/InkedScreenshot_20200420-120442_COVID   Safe Paths_LI 1.jpg 
https://www.jotform.com/uploads/AppQuality/201096241235345/4631877657423941871/InkedScreenshot_20200420-120501_Docs_LI.jpg

**Comment by matteocrippa** [comment]
@vedhakannan would you mind reformat the message and provide further details, eg. what's the version of the app?

**Comment by vedhakannan** [comment]
updated the issue as per "version 0.9.5"

**Comment by matteocrippa** [comment]
This applies to all the language as far the description is not localizable and the TOS is a link to a static resource.

**Comment by summetj** [comment]
@matteocrippa Is this a "won'tfix" and should be closed?

**Comment by matteocrippa** [comment]
@summetj prolly, consider that till we don't have it localizable, it will stay en only

**Comment by summetj** [comment]
Looks like these two strings have specific recommendations for improvement which should be ran by the translation team:

Dashboard > "Ultime novità" section > autorità "sanitarie" and not "sanitare"
Dashboard > Informazioni > Missione section > "l'interazione" and not "l'intereazione"


Otherwise the EULA/Legal will remain English until/unless we get those translated as well.

**Comment by matteocrippa** [comment]
@summetj that two strings were already fixed more than a week ago, I'm taking care of italian localisation. Just double check in lokalise right now as double confirmation

**Comment by summetj** [comment]
@matteocrippa Great thanks! I'm closing the issue.
