### ISSUE TITLE
On Clicking "Latest News " - Error 404 is displaying

### ISSUE THREAD

**Issue by ShreyaaSahu** [tripleblindmarket/covid-safe-paths#645]
## Version

- Type of phone: iPhone
- OS Version: 13.3
- Model: iPhone XR

## Steps to reproduce

1. Open the App
2.click on Hamburger Option on top-right of screen
3.click on "Latest News" option .

![MicrosoftTeams-image](https://user-images.githubusercontent.com/64080646/80095799-2c166b00-8586-11ea-9c9d-71c23efd1f4d.png)

**Comment by kenpugsley** [comment]
Closing.  Was an issue with the https://covidsafepaths.org/in-app-news page, but seems to have been resolved.

**Comment by ShreyaaSahu** [comment]
yes , this is resolved now.
