### ISSUE TITLE
After User Inactive the Location in menu , App is still showing green instead of red in " No Data Match screen "

### ISSUE THREAD

**Issue by ShreyaaSahu** [tripleblindmarket/covid-safe-paths#646]
## Version

- Type of phone: iPhone
- OS Version: ios 13.3
- Model: iPhone XR

## Steps to reproduce

1.Open the App
2.Click on Hamburger Menu Option 
3.Location is already Active 
4.Go back to "No Data Match / No Known Contact Screen" 
5.Screen will display with green 
6. Click on "Location Inactive" - first option on the top of Menu in Hamburger Menu Option 
7.Go back to "No Data Match / No Known Contact Screen"
8.Screen will display with green  instead of Red

![IMG-4553](https://user-images.githubusercontent.com/64080646/80096981-2588f300-8588-11ea-99e0-65ff55e2220a.PNG)
![IMG-4554](https://user-images.githubusercontent.com/64080646/80096989-2883e380-8588-11ea-99ad-eee0f56513a3.PNG)
![IMG-4555](https://user-images.githubusercontent.com/64080646/80097007-32a5e200-8588-11ea-9e89-c1ad1bcac8f5.PNG)
![IMG-4556](https://user-images.githubusercontent.com/64080646/80097021-36d1ff80-8588-11ea-8450-1303fc150dc1.PNG)

## Expected Behavior

Red  instead of green  in " No Data Match screen "

![IMG-4552](https://user-images.githubusercontent.com/64080646/80096719-a1367000-8587-11ea-9d9a-2c4af9716235.PNG)

**Comment by Krish023** [comment]
Can you please assign it to me. I will look at this issue.

**Comment by Krish023** [comment]
Hi, @ShreyaaSahu is this issue only on iOS?

**Comment by ShreyaaSahu** [comment]
hi , @Krish023 this issue is also in Android .

**Comment by Niniya173** [comment]
Same issue is identified in iPhone 5s, version 11.2.6 and app version 1.0.1
