### ISSUE TITLE
Errors importing Google Location History

### ISSUE THREAD

**Issue by AdamLeonSmith** [tripleblindmarket/covid-safe-paths#672]
Testing on the develop branch, when importing a google takeout zip the log file is full of errors:

[INFO] Attempting to open file "file:///data/user/0/org.pathcheck.covidsafepaths/cache/Takeout-2020-04-24T11:54:32.837Z/Takeout/Location History/Semantic Location History/2020/2020_MARCH.json" again [Error: ENOENT: No content provider: /data/user/0/org.pathcheck.covidsafepaths/cache/Takeout-2020-04-24T11:54:32.837Z/Takeout/Location History/Semantic Location History/2020/2020_MARCH.json, open '/data/user/0/org.pathcheck.covidsafepaths/cache/Takeout-2020-04-24T11:54:32.837Z/Takeout/Location History/Semantic Location History/2020/2020_MARCH.json']

**Comment by sergesemashko** [comment]
@AdamLeonSmith , what device and OS version have you tried on?

**Comment by AdamLeonSmith** [comment]
Emulated Pixel 3a with Android 10.  Thanks.
