### ISSUE TITLE
Navigation issues in V1.0 updated setup sequence.

### ISSUE THREAD

**Issue by diarmidmackenzie** [tripleblindmarket/covid-safe-paths#675]
## Version

V1.0.0
- Android 9
- Moto G7

## Steps to reproduce

Multiple navigation issues in the startup flow.

By fast the worst is when you get to the HA screen.  Having entered your HA, you then have to go "back" to go forward.  And the back button is in the top left hand corner, which doesn't match any of the navigation patterns the user has seen up to that point.

Vedha didn;t spot that back button, so tried the Android back button, and at this stage, that just closes the app.

I think most users will fail to get past this stage without closing the app themselves or hitting the back button.

There are a number of other navigation issues around this initial flow.  None so critical, but in combination they do make things even worse.
- You can't go back on any of the opening screens.  That was OK before as they were mostly just messages, with no config, but now e.g. the location screen is directly after tha HAs.  Totally legitimate that you might want to go back & tweak your HA settings, but there is no back button.  Android back button closes the app.
- If you do close the app (whether using Android back button, or by other means), there are some odd things in the flow:
- You have to accept the Icense agreement again, which feels odd.
- You *don't* have to enter an HA again, if you entered it already.  But the prompt tells you that you have to.  There is no adjustment to the text to reflect the fact that you have done thisstep already - I guess the design didn't anticipate the user having to come bak a 2nd time.  So the text says: "... you will need to subscribe to a health authority" even tough you already have.
- When you have not yet entered a Health Authority, I would suggest the "Next" button be labelled "Later" (or "Skip").
- It is inconsistent that you can skip HA setup, but not skip location setup (even though you can turn location off again in-app later!).

## Expected Behavior

Expectations are:
- A seamless setup experience, where I keep moving forward and don't have ot move back
- If I do need to move back, the back controls should be clerly visible and the ANdroid Back button should also work.
- HA & Location screens should be consistent with regard to navigation (can I go back?) and whether I can skip.
- If I end up repeating after closing the app, we should have a consistent paradigm on whether config /choices need to be re-entered.  My preference should be that choices doon't need to be re-entered, but I value consistency most of all.

**Comment by diarmidmackenzie** [comment]
Some screenshots.

Here is the HA selection screen.  The back button is in the top left.  This made sense previously when you had navigated to the screen via the dashboard link in the top right of the app, but in this new context it makes no sense at all.

![image](https://user-images.githubusercontent.com/16045703/80216186-f7fe8100-863d-11ea-82d3-57e55b85cf7c.png)

Here's the previous screen.  No "Back" button, and "Next" would be better as "Later" or "Skip" until you have set an HA.  Then when you have set an HA, it should no longer say "you need to set an HA".  But even better would be not having to come back to this screen again after setting your HA.

![image](https://user-images.githubusercontent.com/16045703/80216311-254b2f00-863e-11ea-8a0f-a0e268bb8f20.png)

Here's the location screen.  No back button on here.

![image](https://user-images.githubusercontent.com/16045703/80216367-3c8a1c80-863e-11ea-843a-a4497dfe8128.png)

**Comment by diarmidmackenzie** [comment]
One further thought:
- To me the ordering of HAs vs. Locations is odd.  Location is something everyone using the app should set up, whether they have an HA available or not.  WHereas HA is something that to start with most users of teh app won't be able to set up.

Therefore HA to me belongs logically after Location.  I think people who don't have an HA available in their area will be confused by the HA setup page (we stil l haven't done enough to help it look OK to people that they don't have any HAs to register with yet).  So let's at least get the location setup (which is not confusing) done before we confuse them...!

**Comment by dganzi** [comment]
Hi all! Thoughts:

1. _You can't go back on any of the opening screens. That was OK before as they were mostly just messages, with no config, but now e.g. the location screen is directly after tha HAs. Totally legitimate that you might want to go back & tweak your HA settings, but there is no back button. Android back button closes the app._
-To my knowledge, there is only one HA that's selectable at the moment. Am I wrong? That would lead me to believe this is relatively okay for now.

2. If backgrounding the app:
_-You have to accept the Icense agreement again, which feels odd._
-The implementation is currently a step and not a recorded DB value
-We should think about this in the future. But I'm not sure this is a blocker

_-You don't have to enter an HA again, if you entered it already. But the prompt tells you that you have to. There is no adjustment to the text to reflect the fact that you have done thisstep already 
-I guess the design didn't anticipate the user having to come bak a 2nd time. So the text says: "... you will need to subscribe to a health authority" even tough you already have.
-When you have not yet entered a Health Authority, I would suggest the "Next" button be labelled "Later" (or "Skip").
-It is inconsistent that you can skip HA setup, but not skip location setup (even though you can turn location off again in-app later!)._
-Will think about this more...

**Comment by dganzi** [comment]
Seems like we can close this?

**Comment by kenpugsley** [comment]
closing.   Health authority selection was remove from the onboarding sequence in #679
