### ISSUE TITLE
Google import instructions improvements

### ISSUE THREAD

**Issue by sergesemashko** [tripleblindmarket/covid-safe-paths#693]
As it was mentioned in the issue [Improve Google Location Data import experience](https://github.com/tripleblindmarket/covid-safe-paths/issues/69#issuecomment-612519987) google location history import process might be too overwhelming for non-technical users due to:
* Amount of steps, accuracy, asynchronous nature(it might take minutes or hours to generate takeout) of import process 
* Google Takeout has only the option to download the entire location history which raises file size concerns:
    * It may eat up the data on a plan
    * There is no evidence the App can process high volume of Takeout data

To conclude, without really good guidance the chances of somebody using import history location are small. 

I could think of several improvement options:
1. Create a multistep screens with 1 instruction per screen and back/next buttons. 
    * Pros:
        * Step by step process limits the room to skip the instruction
    * Cons:
        * Instruction update requires a App releases
        * Translation overhead
2. Move instruction to the web site and link out from the app:
    * Pros:
        * It's easier to update instructions on site than release a new app version
    * Cons: 
        * Site has to be adjusted to accommodate the instructions page

General note, going through import process on a phone is a bit annoying as it requires switching between apps (in case of current import state and option 1) or tabs in mobile browser (in case of option 2). I suggest advising users making an import on desktop/laptop.

**Comment by tstirrat** [comment]
Great options here, discussing on slack in the UX channel! Designers and UX researchers are not all using github, so I'll close this external issue.

Anyone who's interested in the progression of this feature should [join us on slack](https://docs.google.com/forms/d/e/1FAIpQLSdzqAxrlrxb_HqLh1KXnfPu1rse4aByS2krL1OYlN3qKChyqA/viewform)!
