### ISSUE TITLE
In Haitian Creole, few Screen contents are still in English -  ios App v1.01  - similar to issue 676  . 

### ISSUE THREAD

**Issue by ShreyaaSahu** [tripleblindmarket/covid-safe-paths#718]
## Version

- Type of phone: iPhone
- OS Version: ios 13.3
- Model: iPhone XR

## Steps to reproduce

1.  Launch App
2.  Select  "kreyol ayisyen" language in drop down 
3.  Below Screens content are in English :

" I accept the licensing agreement " section
![IMG-4633](https://user-images.githubusercontent.com/64080646/80574287-31106a00-8a1f-11ea-939a-f08faa09637c.PNG)

" Skip this Step "
![IMG-4634](https://user-images.githubusercontent.com/64080646/80574296-353c8780-8a1f-11ea-9522-4bad78530e35.PNG)

 Menu  --> " Legal "  --> Legal Page
![IMG-4635](https://user-images.githubusercontent.com/64080646/80574326-3f5e8600-8a1f-11ea-839a-56c6db0f1e65.PNG)

## Expected Behavior
Everything in Selected Language  .

**Comment by NaziyaNazir** [comment]
Same issue is seen for Android also.

**Comment by Niniya173** [comment]
I also find the same issue in iPhone 5s, app version 1.0.1 and OS version 11.2.6

**Comment by summetj** [comment]
I expect that the "legal" page is that way because we only have the EULA in English right now. The others should definitely be translated.

**Comment by Niniya173** [comment]
Same issue is in the 'Latest News' screen, 'Choose Health Authority' Screen and in the 'About' Screen

Attaching the screenshots,
![image](https://user-images.githubusercontent.com/64129755/80720854-24713c00-8b1b-11ea-963e-bde87c8e756a.png)
![image](https://user-images.githubusercontent.com/64129755/80720889-30f59480-8b1b-11ea-86e9-f95252655e4d.png)
![image](https://user-images.githubusercontent.com/64129755/80720930-3b179300-8b1b-11ea-8f94-89c0f7a9d972.png)
