### ISSUE TITLE
Dashbord shows Location Active though user tapped "skip this step" for location permissions - android App v1.0.1

### ISSUE THREAD

**Issue by NaziyaNazir** [tripleblindmarket/covid-safe-paths#719]
**Version**
Type of phone: Android
OS Version: 9
Model: Realme U1

**Steps to reproduce**
1. Launch App
2. Tap on "Get Started"
3. Accept the Licensing agreement
4. Tap Next twice and click on "Set up my phone"
5. Tap "Skip this step". Location access is shown in red cross mark
6. Tap on "Finish Setup" to navigate to Home screen
7. Navigate to Dashboard

**Expected Behavior**
"Location Inactive" should be shown in Dashboard

**Actual Behavior**
"Location Active" is shown in Dashboard

**Comment by NaziyaNazir** [comment]
![Screenshot_2020-04-29-14-02-20-92_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80576441-cf51ff00-8a22-11ea-9ef1-2d76fd89603a.png)

**Comment by denispapakul** [comment]
I can look into this issue.

**Comment by diarmidmackenzie** [comment]
I saw a number of problems in this area.

It looks as though there are 2 settings here:
- The app's view of whether location tracking is enabled or not
- The OS view of what permissions the app has.

If location permissions are denied (or not yet requested) at the OS level, it seems the app is displaying the "location tracking" status as recorded in the app.  But if the underlying permissions are not enabled, this gives the user the wrong picture.

Note that the App permissions can be in one of 3 states:
- Not yet requested
- Requested & granted
- Requested and denied.

So there are multiple scenarios to consider

For *display* of location status ideally we should show a combined status indicating OS-level permissions + app-level setting.

For "toggle" of location status, it's more complicated.

"on" should only show if OS-level permissions are available & the app-level setting is "on".  When we toggle to off, I think we should change the app-level setting, but leave the OS permissions along.

"off" may show in a number of cases:
- permissions granted, in which case just toggle app-level setting to "on"
- permissions not yet requested, in which case request permissions, and set app-level setting to "on" (in case user says "no" to the permissions request we drop through to the next case).
- permissions already requested and denied.  In this case I believe the App may not be able to re-request permissions (whether they can or not is in fact yet another bit of state I think).  If permissions can be requested again, great - do it.  If they can't be, the APp will need to display an error with guidance to the user as to how to enable location settings for the app (deep in the OS app permissions settings).

**Comment by diarmidmackenzie** [comment]
This needs retesting after fix.

Also there is yet another layer of config to consider.  As well as the app not having permissions to access location data, there is also an option to disble location altogether at the device level.

Again, the App should report location as inactive, and provide appropriate remdial guidance, where this is the case.
