### ISSUE TITLE
" Learn more about Covid SafePaths " link in Latest News is displaying error - ios app v1.0.1

### ISSUE THREAD

**Issue by ShreyaaSahu** [tripleblindmarket/covid-safe-paths#731]
## Version

- Type of phone:  iPhone
- OS Version: ios 13.3
- Model: XR

## Steps to reproduce
1. Open the App
2. Open Hamburger menu
3. select "Latest News "
4. SafePath News screen will open
5. click on link " Learn more about Covid SafePaths "
6. It will display error .

![IMG-4655](https://user-images.githubusercontent.com/64080646/80694198-cb40e280-8af1-11ea-9d56-d00d94b0fe47.PNG)

![IMG-4649](https://user-images.githubusercontent.com/64080646/80694223-d1cf5a00-8af1-11ea-8b67-c1845db6f1b5.PNG)

## Expected Behavior

Display Content

**Comment by NaziyaNazir** [comment]
Issue exists in Android 9 as well.
![Screenshot_2020-04-30-12-39-04-13_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80704361-106d1080-8b02-11ea-8444-0bd67e0369e3.png)

**Comment by summetj** [comment]
@skusunam  is working on this one.

**Comment by skusunam** [comment]
Did some digging and here is the problem:

We use this internal URL (https://covidsafepaths.org/in-app-news) when we navigate to "Latest News" on the App. This URL has a clickable link for "Learn more about Covid SafePaths" which is pointing to wrong/in-correct URL: http://localhost:3000/ and that is why we see the error page.

**Comment by summetj** [comment]
Sounds like an easy fix, go for it! Just make sure to include the keyword "closes" or "fixes" in front of the issue number inside your pull request description. (e.g. "Fixes #731") so that GitHub will link the pull request to this issue and auto-close it when the pull request is accepted.

**Comment by summetj** [comment]
Ok, I understand the issue now. The URL in the app is fine, but that webpage has a broken link. I have informed the website team of this issue (but am leaving the issue open in github until they fix it.)

**Comment by skusunam** [comment]
@summetj Looks like website team fixed this link and it is working fine now. I just validated and you can validate too by going to this URL [https://covidsafepaths.org/in-app-news](https://covidsafepaths.org/in-app-news) and clicking "Learn more about Covid SafePaths" link. I tested this on the ios simulator too.
