### ISSUE TITLE
Contributing Language Support/ Translation/ Localization - Lokalise

### ISSUE THREAD

**Issue by alpita-masurkar** [tripleblindmarket/covid-safe-paths#753]
## Issue type- Localization, Contributing Language Support Guidelines

We've now officially entered into a collaboration with **Lokalise** for our translations.
What this means for us:

- Our translation process is automated with a pleasant UI and makes it easier to see new updates to the English content, see screenshots of where and how the content will appear and translate them.
- **All new translations going forward and updates to the existing ones will be done on Lokalise**. We're constantly keeping the content updated on Lokalise
- **Please do not create a new PR on github directly for adding translation.** There's content beyond the json file in locales that goes on the app and needs translation. Also, sometimes, there are small changes in the English content or maybe a new key gets added, or we accidentally forget to translate some key, all of these issues are very subtle but can affect the user experience in the localized context. It is helpful to work on Lokalise and spot and fix these.  
- **If you would like to contribute a new language or translate content**, create an issue here on Github and get in touch with me @alpita-masurkar or @tstirrat and we'll add you to Lokalise. We'll need your email id for this.
- We also have a very active and helpful **Slack channel**. If you're on slack, you can also reach out to us there. If you're not on Slack and would like to get added there, please let us know and we can invite you.

Please reach out if you have any questions and we'd be happy to respond/help.

Thank you.
-Alpita

**Comment by alpita-masurkar** [comment]
If possible, can we also link this on the CONTRIBUTING.md file?
It'd be really helpful as there are some who are not on Slack and contributing language PRs here. It is a duplication of efforts for them.

**Comment by tstirrat** [comment]
https://github.com/tripleblindmarket/covid-safe-paths/wiki/Localization-Contributing-Guidelines
